class BillRunner{
public static void main(String[]a){
	System.out.println("main started");

    Bill firstBill=new Bill();
	firstBill.billId=1;
	firstBill.billAmountWithTax=120.99;
	firstBill.planType="Monthly plan";
	firstBill.billIssueDate="21-07-2025";
	firstBill.paymentMethod="UPI";
	firstBill.billDueDate="25-07-2025";
	firstBill.isTaxInclusive=true;
	 firstBill.isBillPaid=false;
	firstBill.isBillOverDue=false;
System.out.println("The first Bill Id is "+firstBill.billId);
System.out.println("The first billAmountWithTax is "+firstBill.billAmountWithTax);
System.out.println("The first planType is "+firstBill.planType);
System.out.println("The first billIssueDate is "+firstBill.billIssueDate);
System.out.println("The first paymentMethod is "+firstBill.paymentMethod);
System.out.println("The first billDueDate is "+firstBill.billDueDate);
System.out.println("The first isTaxInclusive "+firstBill.isTaxInclusive);
System.out.println("The first isBillPaid is "+firstBill.isBillPaid);
System.out.println("The first isBillOverDue is "+firstBill.isBillOverDue);


Bill secondBill=new Bill();
	secondBill.billId=2;
	secondBill.billAmountWithTax=506.66;
	secondBill.planType="Quaterly  plan";
	secondBill.billIssueDate="28-07-2025";
	secondBill.paymentMethod="debit card";
	secondBill.billDueDate="30-07-2025";
	secondBill.isTaxInclusive=true;
	secondBill.isBillPaid=false;
	secondBill.isBillOverDue=false;
System.out.println("The second Id is "+secondBill.billId);
System.out.println("The second billAmountWithTax is "+secondBill.billAmountWithTax);
System.out.println("The secondsecond planType is "+secondBill.planType);
System.out.println("The second billIssueDate is "+secondBill.billIssueDate);
System.out.println("The second paymentMethod is "+secondBill.paymentMethod);
System.out.println("The second billDueDate is "+secondBill.billDueDate);
System.out.println("The second isTaxInclusive "+secondBill.isTaxInclusive);
System.out.println("The second isBillPaid is "+secondBill.isBillPaid);
System.out.println("The second isBillOverDue is "+secondBill.isBillOverDue);

Bill thirdBill=new Bill();
	thirdBill.billId=3;
	thirdBill.billAmountWithTax=2500.66;
	thirdBill.planType="yearly  plan";
	thirdBill.billIssueDate="20-06-2025";
	thirdBill.paymentMethod="debit card";
	thirdBill.billDueDate="30-06-2025";
	thirdBill.isTaxInclusive=true;
	thirdBill.isBillPaid=false;
	thirdBill.isBillOverDue=false;
System.out.println("The third Id is "+thirdBill.billId);
System.out.println("The third billAmountWithTax is "+thirdBill.billAmountWithTax);
System.out.println("The third planType is "+thirdBill.planType);
System.out.println("The third billIssueDate is "+thirdBill.billIssueDate);
System.out.println("The third paymentMethod is "+thirdBill.paymentMethod);
System.out.println("The third billDueDate is "+thirdBill.billDueDate);
System.out.println("The third isTaxInclusive "+thirdBill.isTaxInclusive);
System.out.println("The third isBillPaid is "+thirdBill.isBillPaid);
System.out.println("The third isBillOverDue is "+thirdBill.isBillOverDue);

Bill fourthBill=new Bill();
	fourthBill.billId=4;
	fourthBill.billAmountWithTax=350.66;
	fourthBill.planType="monthly plan";
	fourthBill.billIssueDate="21-06-2025";
	fourthBill.paymentMethod="Amazon Wallet";
	fourthBill.billDueDate="29-06-2025";
	fourthBill.isTaxInclusive=true;
	fourthBill.isBillPaid=false;
	fourthBill.isBillOverDue=false;
System.out.println("The fourth Id is "+fourthBill.billId);
System.out.println("The fourth billAmountWithTax is "+fourthBill.billAmountWithTax);
System.out.println("The fourth planType is "+fourthBill.planType);
System.out.println("The fourth billIssueDate is "+fourthBill.billIssueDate);
System.out.println("The fourth paymentMethod is "+fourthBill.paymentMethod);
System.out.println("The fourth billDueDate is "+fourthBill.billDueDate);
System.out.println("The fourth isTaxInclusive "+fourthBill.isTaxInclusive);
System.out.println("The fourth isBillPaid is "+fourthBill.isBillPaid);
System.out.println("The fourth isBillOverDue is "+fourthBill.isBillOverDue);

Bill fifthBill=new Bill();
	fifthBill.billId=5;
	fifthBill.billAmountWithTax=350.66;
	fifthBill.planType="yearly  plan";
	fifthBill.billIssueDate="21-06-2025";
	fifthBill.paymentMethod="credit card";
	fifthBill.billDueDate="29-06-2025";
	fifthBill.isTaxInclusive=true;
	fifthBill.isBillPaid=false;
	fifthBill.isBillOverDue=false;
System.out.println("The fifth Id is "+fifthBill.billId);
System.out.println("The fifth billAmountWithTax is "+fifthBill.billAmountWithTax);
System.out.println("The fifth planType is "+fifthBill.planType);
System.out.println("The fifth billIssueDate is "+fifthBill.billIssueDate);
System.out.println("The fifth paymentMethod is "+fifthBill.paymentMethod);
System.out.println("The fifth billDueDate is "+fifthBill.billDueDate);
System.out.println("The fifth isTaxInclusive "+fifthBill.isTaxInclusive);
System.out.println("The fifth isBillPaid is "+fifthBill.isBillPaid);
System.out.println("The fifth isBillOverDue is "+fifthBill.isBillOverDue);

Bill sixthBill=new Bill();
	sixthBill.billId=6;
	sixthBill.billAmountWithTax=1000.66;
	sixthBill.planType="six month plan";
	sixthBill.billIssueDate="20-10-2025";
	sixthBill.paymentMethod="debit card";
	sixthBill.billDueDate="29-10-2025";
	sixthBill.isTaxInclusive=true;
	sixthBill.isBillPaid=false;
	sixthBill.isBillOverDue=false;
System.out.println("The sixth Id is "+sixthBill.billId);
System.out.println("The sixth billAmountWithTax is "+sixthBill.billAmountWithTax);
System.out.println("The sixth planType is "+sixthBill.planType);
System.out.println("The sixth billIssueDate is "+sixthBill.billIssueDate);
System.out.println("The sixth paymentMethod is "+sixthBill.paymentMethod);
System.out.println("The sixth billDueDate is "+sixthBill.billDueDate);
System.out.println("The sixth isTaxInclusive "+sixthBill.isTaxInclusive);
System.out.println("The sixth isBillPaid is "+sixthBill.isBillPaid);
System.out.println("The sixth isBillOverDue is "+sixthBill.isBillOverDue);

Bill seventhBill=new Bill();
	seventhBill.billId=7;
	seventhBill.billAmountWithTax=1200.66;
	seventhBill.planType="seven month plan";
	seventhBill.billIssueDate="19-11-2025";
	seventhBill.paymentMethod="debit card";
	seventhBill.billDueDate="27-10-2025";
	seventhBill.isTaxInclusive=true;
	seventhBill.isBillPaid=false;
	seventhBill.isBillOverDue=false;
System.out.println("The seventh Id is "+seventhBill.billId);
System.out.println("The seventh billAmountWithTax is "+seventhBill.billAmountWithTax);
System.out.println("The seventh planType is "+seventhBill.planType);
System.out.println("The seventh billIssueDate is "+seventhBill.billIssueDate);
System.out.println("The seventh paymentMethod is "+seventhBill.paymentMethod);
System.out.println("The seventh billDueDate is "+seventhBill.billDueDate);
System.out.println("The seventh isTaxInclusive "+seventhBill.isTaxInclusive);
System.out.println("The seventh isBillPaid is "+seventhBill.isBillPaid);
System.out.println("The seventh isBillOverDue is "+seventhBill.isBillOverDue);

Bill eighthBill=new Bill();
	eighthBill.billId=8;
	eighthBill.billAmountWithTax=1400.66;
	eighthBill.planType="eight month plan";
	eighthBill.billIssueDate="19-07-2025";
	eighthBill.paymentMethod="UPI";
	eighthBill.billDueDate="27-07-2025";
	eighthBill.isTaxInclusive=true;
	eighthBill.isBillPaid=false;
	eighthBill.isBillOverDue=false;
System.out.println("The eighth Id is "+eighthBill.billId);
System.out.println("The eighth billAmountWithTax is "+eighthBill.billAmountWithTax);
System.out.println("The eighth planType is "+eighthBill.planType);
System.out.println("The eighth billIssueDate is "+eighthBill.billIssueDate);
System.out.println("The eighth paymentMethod is "+eighthBill.paymentMethod);
System.out.println("The eighth billDueDate is "+eighthBill.billDueDate);
System.out.println("The eighth isTaxInclusive "+eighthBill.isTaxInclusive);
System.out.println("The eighth isBillPaid is "+eighthBill.isBillPaid);
System.out.println("The eighth isBillOverDue is "+eighthBill.isBillOverDue);

Bill ninthBill=new Bill();
	ninthBill.billId=9;
	ninthBill.billAmountWithTax=1900.00;
	ninthBill.planType="ten month plan";
	ninthBill.billIssueDate="18-05-2025";
	ninthBill.paymentMethod=" net banking";
	ninthBill.billDueDate="27-07-2025";
	ninthBill.isTaxInclusive=true;
	ninthBill.isBillPaid=false;
	ninthBill.isBillOverDue=false;
System.out.println("The ninth Id is "+ninthBill.billId);
System.out.println("The ninth billAmountWithTax is "+ninthBill.billAmountWithTax);
System.out.println("The ninth planType is "+ninthBill.planType);
System.out.println("The ninth billIssueDate is "+ninthBill.billIssueDate);
System.out.println("The ninth paymentMethod is "+ninthBill.paymentMethod);
System.out.println("The ninth billDueDate is "+ninthBill.billDueDate);
System.out.println("The ninth isTaxInclusive "+ninthBill.isTaxInclusive);
System.out.println("The ninth isBillPaid is "+ninthBill.isBillPaid);
System.out.println("The ninth isBillOverDue is "+ninthBill.isBillOverDue);

Bill tenthBill=new Bill();
	tenthBill.billId=10;
	tenthBill.billAmountWithTax=1500.66;
	tenthBill.planType="nine month plan";
	tenthBill.billIssueDate="06-08-2025";
	tenthBill.paymentMethod="debit card";
	tenthBill.billDueDate="27-08-2025";
	tenthBill.isTaxInclusive=true;
	tenthBill.isBillPaid=false;
	tenthBill.isBillOverDue=false;
System.out.println("The tenth Id is "+tenthBill.billId);
System.out.println("The tenth billAmountWithTax is "+tenthBill.billAmountWithTax);
System.out.println("The tenth planType is "+tenthBill.planType);
System.out.println("The tenth billIssueDate is "+tenthBill.billIssueDate);
System.out.println("The tenth paymentMethod is "+tenthBill.paymentMethod);
System.out.println("The tenth billDueDate is "+tenthBill.billDueDate);
System.out.println("The tenth isTaxInclusive "+tenthBill.isTaxInclusive);
System.out.println("The tenth isBillPaid is "+tenthBill.isBillPaid);
System.out.println("The tenth isBillOverDue is "+tenthBill.isBillOverDue);

Bill eleventhBill=new Bill();
	eleventhBill.billId=11;
	eleventhBill.billAmountWithTax=290.66;
	eleventhBill.planType="25 days plan";
	eleventhBill.billIssueDate="15-04-2025";
	eleventhBill.paymentMethod="debit card";
	eleventhBill.billDueDate="25-04-2025";
	eleventhBill.isTaxInclusive=true;
	eleventhBill.isBillPaid=false;
	eleventhBill.isBillOverDue=false;
System.out.println("The eleventh Id is "+eleventhBill.billId);
System.out.println("The eleventh  billAmountWithTax is "+eleventhBill.billAmountWithTax);
System.out.println("The eleventh  planType is "+eleventhBill.planType);
System.out.println("The eleventh  billIssueDate is "+eleventhBill.billIssueDate);
System.out.println("The eleventh  paymentMethod is "+eleventhBill.paymentMethod);
System.out.println("The eleventh  billDueDate is "+eleventhBill.billDueDate);
System.out.println("The eleventh  isTaxInclusive "+eleventhBill.isTaxInclusive);
System.out.println("The eleventh  isBillPaid is "+eleventhBill.isBillPaid);
System.out.println("The eleventh  isBillOverDue is "+eleventhBill.isBillOverDue);



Bill twelthBill=new Bill();
	twelthBill.billId=12;
	twelthBill.billAmountWithTax=290.66;
	twelthBill.planType="25 days plan";
	twelthBill.billIssueDate="19-02-2025";
	twelthBill.paymentMethod=" cash";
	twelthBill.billDueDate="25-02-2025";
	twelthBill.isTaxInclusive=true;
	twelthBill.isBillPaid=false;
	twelthBill.isBillOverDue=false;
System.out.println("The twelth Id is "+twelthBill.billId);
System.out.println("The twelth  billAmountWithTax is "+twelthBill.billAmountWithTax);
System.out.println("The twelth  planType is "+twelthBill.planType);
System.out.println("The twelth  billIssueDate is "+twelthBill.billIssueDate);
System.out.println("The twelth  paymentMethod is "+twelthBill.paymentMethod);
System.out.println("The twelth  billDueDate is "+twelthBill.billDueDate);
System.out.println("The twelth  isTaxInclusive "+twelthBill.isTaxInclusive);
System.out.println("The twelth  isBillPaid is "+twelthBill.isBillPaid);
System.out.println("The twelth  isBillOverDue is "+twelthBill.isBillOverDue);

Bill thirteenthBill=new Bill();
	thirteenthBill.billId=12;
	thirteenthBill.billAmountWithTax=290.66;
	thirteenthBill.planType="25 days plan";
	thirteenthBill.billIssueDate="17-03-2025";
	thirteenthBill.paymentMethod="debit card";
	thirteenthBill.billDueDate="25-03-2025";
	thirteenthBill.isTaxInclusive=true;
	thirteenthBill.isBillPaid=false;
	thirteenthBill.isBillOverDue=false;
System.out.println("The thirteenth Id is "+thirteenthBill.billId);
System.out.println("The thirteenth  billAmountWithTax is "+thirteenthBill.billAmountWithTax);
System.out.println("The thirteenth  planType is "+thirteenthBill.planType);
System.out.println("The thirteenth  billIssueDate is "+thirteenthBill.billIssueDate);
System.out.println("The thirteenth  paymentMethod is "+thirteenthBill.paymentMethod);
System.out.println("The thirteenth  billDueDate is "+thirteenthBill.billDueDate);
System.out.println("The thirteenth  isTaxInclusive "+thirteenthBill.isTaxInclusive);
System.out.println("The thirteenth  isBillPaid is "+thirteenthBill.isBillPaid);
System.out.println("The thirteenth  isBillOverDue is "+thirteenthBill.isBillOverDue);


Bill fourteenthBill=new Bill();
	fourteenthBill.billId=12;
	fourteenthBill.billAmountWithTax=290.66;
	fourteenthBill.planType="25 days plan";
	fourteenthBill.billIssueDate="18-06-2025";
	fourteenthBill.paymentMethod="credit card";
	fourteenthBill.billDueDate="21-06-2025";
	fourteenthBill.isTaxInclusive=true;
	fourteenthBill.isBillPaid=false;
	fourteenthBill.isBillOverDue=false;
System.out.println("The fourteenth Id is "+fourteenthBill.billId);
System.out.println("The fourteenth  billAmountWithTax is "+fourteenthBill.billAmountWithTax);
System.out.println("The fourteenth  planType is "+fourteenthBill.planType);
System.out.println("The fourteenth  billIssueDate is "+fourteenthBill.billIssueDate);
System.out.println("The fourteenth  paymentMethod is "+fourteenthBill.paymentMethod);
System.out.println("The fourteenth  billDueDate is "+fourteenthBill.billDueDate);
System.out.println("The fourteenth  isTaxInclusive "+fourteenthBill.isTaxInclusive);
System.out.println("The fourteenth  isBillPaid is "+fourteenthBill.isBillPaid);
System.out.println("The fourteenth  isBillOverDue is "+fourteenthBill.isBillOverDue);


Bill fifteenthBill = new Bill();
fifteenthBill.billId = 15;
fifteenthBill.billAmountWithTax = 320.75;
fifteenthBill.planType = "30 days plan";
fifteenthBill.billIssueDate = "01-09-2025";
fifteenthBill.paymentMethod = "debit card";
fifteenthBill.billDueDate = "10-09-2025";
fifteenthBill.isTaxInclusive = true;
fifteenthBill.isBillPaid = true;
fifteenthBill.isBillOverDue = false;
System.out.println("The fifteenth Id is " + fifteenthBill.billId);
System.out.println("The fifteenth billAmountWithTax is " + fifteenthBill.billAmountWithTax);
System.out.println("The fifteenth planType is " + fifteenthBill.planType);
System.out.println("The fifteenth billIssueDate is " + fifteenthBill.billIssueDate);
System.out.println("The fifteenth paymentMethod is " + fifteenthBill.paymentMethod);
System.out.println("The fifteenth billDueDate is " + fifteenthBill.billDueDate);
System.out.println("The fifteenth isTaxInclusive " + fifteenthBill.isTaxInclusive);
System.out.println("The fifteenth isBillPaid is " + fifteenthBill.isBillPaid);
System.out.println("The fifteenth isBillOverDue is " + fifteenthBill.isBillOverDue);

Bill sixteenthBill = new Bill();
sixteenthBill.billId = 16;
sixteenthBill.billAmountWithTax = 410.90;
sixteenthBill.planType = "45 days plan";
sixteenthBill.billIssueDate = "05-09-2025";
sixteenthBill.paymentMethod = "UPI";
sixteenthBill.billDueDate = "20-09-2025";
sixteenthBill.isTaxInclusive = false;
sixteenthBill.isBillPaid = false;
sixteenthBill.isBillOverDue = true;
System.out.println("The sixteenth Id is " + sixteenthBill.billId);
System.out.println("The sixteenth billAmountWithTax is " + sixteenthBill.billAmountWithTax);
System.out.println("The sixteenth planType is " + sixteenthBill.planType);
System.out.println("The sixteenth billIssueDate is " + sixteenthBill.billIssueDate);
System.out.println("The sixteenth paymentMethod is " + sixteenthBill.paymentMethod);
System.out.println("The sixteenth billDueDate is " + sixteenthBill.billDueDate);
System.out.println("The sixteenth isTaxInclusive " + sixteenthBill.isTaxInclusive);
System.out.println("The sixteenth isBillPaid is " + sixteenthBill.isBillPaid);
System.out.println("The sixteenth isBillOverDue is " + sixteenthBill.isBillOverDue);

Bill seventeenthBill = new Bill();
seventeenthBill.billId = 17;
seventeenthBill.billAmountWithTax = 150.00;
seventeenthBill.planType = "15 days plan";
seventeenthBill.billIssueDate = "12-08-2025";
seventeenthBill.paymentMethod = "cash";
seventeenthBill.billDueDate = "25-08-2025";
seventeenthBill.isTaxInclusive = true;
seventeenthBill.isBillPaid = false;
seventeenthBill.isBillOverDue = false;
System.out.println("The seventeenth Id is " + seventeenthBill.billId);
System.out.println("The seventeenth billAmountWithTax is " + seventeenthBill.billAmountWithTax);
System.out.println("The seventeenth planType is " + seventeenthBill.planType);
System.out.println("The seventeenth billIssueDate is " + seventeenthBill.billIssueDate);
System.out.println("The seventeenth paymentMethod is " + seventeenthBill.paymentMethod);
System.out.println("The seventeenth billDueDate is " + seventeenthBill.billDueDate);
System.out.println("The seventeenth isTaxInclusive " + seventeenthBill.isTaxInclusive);
System.out.println("The seventeenth isBillPaid is " + seventeenthBill.isBillPaid);
System.out.println("The seventeenth isBillOverDue is " + seventeenthBill.isBillOverDue);

Bill eighteenthBill = new Bill();
eighteenthBill.billId = 18;
eighteenthBill.billAmountWithTax = 199.99;
eighteenthBill.planType = "20 days plan";
eighteenthBill.billIssueDate = "15-10-2025";
eighteenthBill.paymentMethod = "net banking";
eighteenthBill.billDueDate = "25-10-2025";
eighteenthBill.isTaxInclusive = false;
eighteenthBill.isBillPaid = true;
eighteenthBill.isBillOverDue = false;
System.out.println("The eighteenth Id is " + eighteenthBill.billId);
System.out.println("The eighteenth billAmountWithTax is " + eighteenthBill.billAmountWithTax);
System.out.println("The eighteenth planType is " + eighteenthBill.planType);
System.out.println("The eighteenth billIssueDate is " + eighteenthBill.billIssueDate);
System.out.println("The eighteenth paymentMethod is " + eighteenthBill.paymentMethod);
System.out.println("The eighteenth billDueDate is " + eighteenthBill.billDueDate);
System.out.println("The eighteenth isTaxInclusive " + eighteenthBill.isTaxInclusive);
System.out.println("The eighteenth isBillPaid is " + eighteenthBill.isBillPaid);
System.out.println("The eighteenth isBillOverDue is " + eighteenthBill.isBillOverDue);

Bill nineteenthBill = new Bill();
nineteenthBill.billId = 19;
nineteenthBill.billAmountWithTax = 370.85;
nineteenthBill.planType = "60 days plan";
nineteenthBill.billIssueDate = "20-09-2025";
nineteenthBill.paymentMethod = "credit card";
nineteenthBill.billDueDate = "20-11-2025";
nineteenthBill.isTaxInclusive = true;
nineteenthBill.isBillPaid = false;
nineteenthBill.isBillOverDue = true;
System.out.println("The nineteenth Id is " + nineteenthBill.billId);
System.out.println("The nineteenth billAmountWithTax is " + nineteenthBill.billAmountWithTax);
System.out.println("The nineteenth planType is " + nineteenthBill.planType);
System.out.println("The nineteenth billIssueDate is " + nineteenthBill.billIssueDate);
System.out.println("The nineteenth paymentMethod is " + nineteenthBill.paymentMethod);
System.out.println("The nineteenth billDueDate is " + nineteenthBill.billDueDate);
System.out.println("The nineteenth isTaxInclusive " + nineteenthBill.isTaxInclusive);
System.out.println("The nineteenth isBillPaid is " + nineteenthBill.isBillPaid);
System.out.println("The nineteenth isBillOverDue is " + nineteenthBill.isBillOverDue);

Bill twentiethBill = new Bill();
twentiethBill.billId = 20;
twentiethBill.billAmountWithTax = 275.50;
twentiethBill.planType = "35 days plan";
twentiethBill.billIssueDate = "25-09-2025";
twentiethBill.paymentMethod = "UPI";
twentiethBill.billDueDate = "30-10-2025";
twentiethBill.isTaxInclusive = false;
twentiethBill.isBillPaid = true;
twentiethBill.isBillOverDue = false;
System.out.println("The twentieth Id is " + twentiethBill.billId);
System.out.println("The twentieth billAmountWithTax is " + twentiethBill.billAmountWithTax);
System.out.println("The twentieth planType is " + twentiethBill.planType);
System.out.println("The twentieth billIssueDate is " + twentiethBill.billIssueDate);
System.out.println("The twentieth paymentMethod is " + twentiethBill.paymentMethod);
System.out.println("The twentieth billDueDate is " + twentiethBill.billDueDate);
System.out.println("The twentieth isTaxInclusive " + twentiethBill.isTaxInclusive);
System.out.println("The twentieth isBillPaid is " + twentiethBill.isBillPaid);
System.out.println("The twentieth isBillOverDue is " + twentiethBill.isBillOverDue);

System.out.println("main ended");
}
}