class BlazzerRunner {
public static void main(String[] args) {
System.out.println("main started");

        Blazzer blazzer1 = new Blazzer();
        blazzer1.blazzerId = 1;
        blazzer1.brand = "Raymond";
        blazzer1.size = "M";
        blazzer1.color = "Black";
        blazzer1.price = 3499.50;
        blazzer1.isWoolen = true;
        blazzer1.isAvailable = true;
        System.out.println("Blazzer 1 ID: " + blazzer1.blazzerId);
        System.out.println("Blazzer 1 Brand: " + blazzer1.brand);
        System.out.println("Blazzer 1 Size: " + blazzer1.size);
        System.out.println("Blazzer 1 Color: " + blazzer1.color);
        System.out.println("Blazzer 1 Price: " + blazzer1.price);
        System.out.println("Blazzer 1 isWoolen: " + blazzer1.isWoolen);
        System.out.println("Blazzer 1 isAvailable: " + blazzer1.isAvailable);

        Blazzer blazzer2 = new Blazzer();
        blazzer2.blazzerId = 2;
        blazzer2.brand = "Allen Solly";
        blazzer2.size = "L";
        blazzer2.color = "Navy Blue";
        blazzer2.price = 4599.75;
        blazzer2.isWoolen = false;
        blazzer2.isAvailable = true;
        System.out.println("Blazzer 2 ID: " + blazzer2.blazzerId);
        System.out.println("Blazzer 2 Brand: " + blazzer2.brand);
        System.out.println("Blazzer 2 Size: " + blazzer2.size);
        System.out.println("Blazzer 2 Color: " + blazzer2.color);
        System.out.println("Blazzer 2 Price: " + blazzer2.price);
        System.out.println("Blazzer 2 isWoolen: " + blazzer2.isWoolen);
        System.out.println("Blazzer 2 isAvailable: " + blazzer2.isAvailable);

        Blazzer blazzer3 = new Blazzer();
        blazzer3.blazzerId = 3;
        blazzer3.brand = "Zara";
        blazzer3.size = "S";
        blazzer3.color = "Grey";
        blazzer3.price = 3999.00;
        blazzer3.isWoolen = true;
        blazzer3.isAvailable = false;
        System.out.println("Blazzer 3 ID: " + blazzer3.blazzerId);
        System.out.println("Blazzer 3 Brand: " + blazzer3.brand);
        System.out.println("Blazzer 3 Size: " + blazzer3.size);
        System.out.println("Blazzer 3 Color: " + blazzer3.color);
        System.out.println("Blazzer 3 Price: " + blazzer3.price);
        System.out.println("Blazzer 3 isWoolen: " + blazzer3.isWoolen);
        System.out.println("Blazzer 3 isAvailable: " + blazzer3.isAvailable);

        Blazzer blazzer4 = new Blazzer();
        blazzer4.blazzerId = 4;
        blazzer4.brand = "Peter England";
        blazzer4.size = "XL";
        blazzer4.color = "Maroon";
        blazzer4.price = 3799.90;
        blazzer4.isWoolen = false;
        blazzer4.isAvailable = true;
        System.out.println("Blazzer 4 ID: " + blazzer4.blazzerId);
        System.out.println("Blazzer 4 Brand: " + blazzer4.brand);
        System.out.println("Blazzer 4 Size: " + blazzer4.size);
        System.out.println("Blazzer 4 Color: " + blazzer4.color);
        System.out.println("Blazzer 4 Price: " + blazzer4.price);
        System.out.println("Blazzer 4 isWoolen: " + blazzer4.isWoolen);
        System.out.println("Blazzer 4 isAvailable: " + blazzer4.isAvailable);

        Blazzer blazzer5 = new Blazzer();
        blazzer5.blazzerId = 5;
        blazzer5.brand = "Van Heusen";
        blazzer5.size = "M";
        blazzer5.color = "Blue";
        blazzer5.price = 4299.95;
        blazzer5.isWoolen = true;
        blazzer5.isAvailable = true;
        System.out.println("Blazzer 5 ID: " + blazzer5.blazzerId);
        System.out.println("Blazzer 5 Brand: " + blazzer5.brand);
        System.out.println("Blazzer 5 Size: " + blazzer5.size);
        System.out.println("Blazzer 5 Color: " + blazzer5.color);
        System.out.println("Blazzer 5 Price: " + blazzer5.price);
        System.out.println("Blazzer 5 isWoolen: " + blazzer5.isWoolen);
        System.out.println("Blazzer 5 isAvailable: " + blazzer5.isAvailable);

        Blazzer blazzer6 = new Blazzer();
        blazzer6.blazzerId = 6;
        blazzer6.brand = "Louis Philippe";
        blazzer6.size = "L";
        blazzer6.color = "Olive Green";
        blazzer6.price = 5299.00;
        blazzer6.isWoolen = false;
        blazzer6.isAvailable = false;
        System.out.println("Blazzer 6 ID: " + blazzer6.blazzerId);
        System.out.println("Blazzer 6 Brand: " + blazzer6.brand);
        System.out.println("Blazzer 6 Size: " + blazzer6.size);
        System.out.println("Blazzer 6 Color: " + blazzer6.color);
        System.out.println("Blazzer 6 Price: " + blazzer6.price);
        System.out.println("Blazzer 6 isWoolen: " + blazzer6.isWoolen);
        System.out.println("Blazzer 6 isAvailable: " + blazzer6.isAvailable);

        Blazzer blazzer7 = new Blazzer();
        blazzer7.blazzerId = 7;
        blazzer7.brand = "H&M";
        blazzer7.size = "S";
        blazzer7.color = "Beige";
        blazzer7.price = 2899.25;
        blazzer7.isWoolen = true;
        blazzer7.isAvailable = true;
        System.out.println("Blazzer 7 ID: " + blazzer7.blazzerId);
        System.out.println("Blazzer 7 Brand: " + blazzer7.brand);
        System.out.println("Blazzer 7 Size: " + blazzer7.size);
        System.out.println("Blazzer 7 Color: " + blazzer7.color);
        System.out.println("Blazzer 7 Price: " + blazzer7.price);
        System.out.println("Blazzer 7 isWoolen: " + blazzer7.isWoolen);
        System.out.println("Blazzer 7 isAvailable: " + blazzer7.isAvailable);

                Blazzer blazzer8 = new Blazzer();
        blazzer8.blazzerId = 8;
        blazzer8.brand = "Marks & Spencer";
        blazzer8.size = "M";
        blazzer8.color = "Brown";
        blazzer8.price = 3199.80;
        blazzer8.isWoolen = false;
        blazzer8.isAvailable = true;
        System.out.println("Blazzer 8 ID: " + blazzer8.blazzerId);
        System.out.println("Blazzer 8 Brand: " + blazzer8.brand);
        System.out.println("Blazzer 8 Size: " + blazzer8.size);
        System.out.println("Blazzer 8 Color: " + blazzer8.color);
        System.out.println("Blazzer 8 Price: " + blazzer8.price);
        System.out.println("Blazzer 8 isWoolen: " + blazzer8.isWoolen);
        System.out.println("Blazzer 8 isAvailable: " + blazzer8.isAvailable);

        Blazzer blazzer9 = new Blazzer();
        blazzer9.blazzerId = 9;
        blazzer9.brand = "Park Avenue";
        blazzer9.size = "L";
        blazzer9.color = "Dark Grey";
        blazzer9.price = 3699.99;
        blazzer9.isWoolen = true;
        blazzer9.isAvailable = true;
        System.out.println("Blazzer 9 ID: " + blazzer9.blazzerId);
        System.out.println("Blazzer 9 Brand: " + blazzer9.brand);
        System.out.println("Blazzer 9 Size: " + blazzer9.size);
        System.out.println("Blazzer 9 Color: " + blazzer9.color);
        System.out.println("Blazzer 9 Price: " + blazzer9.price);
        System.out.println("Blazzer 9 isWoolen: " + blazzer9.isWoolen);
        System.out.println("Blazzer 9 isAvailable: " + blazzer9.isAvailable);

        Blazzer blazzer10 = new Blazzer();
        blazzer10.blazzerId = 10;
        blazzer10.brand = "Arrow";
        blazzer10.size = "XL";
        blazzer10.color = "White";
        blazzer10.price = 4899.45;
        blazzer10.isWoolen = false;
        blazzer10.isAvailable = true;
        System.out.println("Blazzer 10 ID: " + blazzer10.blazzerId);
        System.out.println("Blazzer 10 Brand: " + blazzer10.brand);
        System.out.println("Blazzer 10 Size: " + blazzer10.size);
        System.out.println("Blazzer 10 Color: " + blazzer10.color);
        System.out.println("Blazzer 10 Price: " + blazzer10.price);
        System.out.println("Blazzer 10 isWoolen: " + blazzer10.isWoolen);
        System.out.println("Blazzer 10 isAvailable: " + blazzer10.isAvailable);

        Blazzer blazzer11 = new Blazzer();
        blazzer11.blazzerId = 11;
        blazzer11.brand = "Mufti";
        blazzer11.size = "M";
        blazzer11.color = "Steel Blue";
        blazzer11.price = 4299.99;
        blazzer11.isWoolen = true;
        blazzer11.isAvailable = false;
        System.out.println("Blazzer 11 ID: " + blazzer11.blazzerId);
        System.out.println("Blazzer 11 Brand: " + blazzer11.brand);
        System.out.println("Blazzer 11 Size: " + blazzer11.size);
        System.out.println("Blazzer 11 Color: " + blazzer11.color);
        System.out.println("Blazzer 11 Price: " + blazzer11.price);
        System.out.println("Blazzer 11 isWoolen: " + blazzer11.isWoolen);
        System.out.println("Blazzer 11 isAvailable: " + blazzer11.isAvailable);

        Blazzer blazzer12 = new Blazzer();
        blazzer12.blazzerId = 12;
        blazzer12.brand = "Next";
        blazzer12.size = "S";
        blazzer12.color = "Cream";
        blazzer12.price = 3099.00;
        blazzer12.isWoolen = false;
        blazzer12.isAvailable = true;
        System.out.println("Blazzer 12 ID: " + blazzer12.blazzerId);
        System.out.println("Blazzer 12 Brand: " + blazzer12.brand);
        System.out.println("Blazzer 12 Size: " + blazzer12.size);
        System.out.println("Blazzer 12 Color: " + blazzer12.color);
        System.out.println("Blazzer 12 Price: " + blazzer12.price);
        System.out.println("Blazzer 12 isWoolen: " + blazzer12.isWoolen);
        System.out.println("Blazzer 12 isAvailable: " + blazzer12.isAvailable);

        Blazzer blazzer13 = new Blazzer();
        blazzer13.blazzerId = 13;
        blazzer13.brand = "Uniqlo";
        blazzer13.size = "L";
        blazzer13.color = "Light Grey";
        blazzer13.price = 3799.55;
        blazzer13.isWoolen = true;
        blazzer13.isAvailable = true;
        System.out.println("Blazzer 13 ID: " + blazzer13.blazzerId);
        System.out.println("Blazzer 13 Brand: " + blazzer13.brand);
        System.out.println("Blazzer 13 Size: " + blazzer13.size);
        System.out.println("Blazzer 13 Color: " + blazzer13.color);
        System.out.println("Blazzer 13 Price: " + blazzer13.price);
        System.out.println("Blazzer 13 isWoolen: " + blazzer13.isWoolen);
        System.out.println("Blazzer 13 isAvailable: " + blazzer13.isAvailable);

        Blazzer blazzer14 = new Blazzer();
        blazzer14.blazzerId = 14;
        blazzer14.brand = "FabIndia";
        blazzer14.size = "XL";
        blazzer14.color = "Indigo";
        blazzer14.price = 3499.00;
        blazzer14.isWoolen = false;
        blazzer14.isAvailable = false;
        System.out.println("Blazzer 14 ID: " + blazzer14.blazzerId);
        System.out.println("Blazzer 14 Brand: " + blazzer14.brand);
        System.out.println("Blazzer 14 Size: " + blazzer14.size);
        System.out.println("Blazzer 14 Color: " + blazzer14.color);
        System.out.println("Blazzer 14 Price: " + blazzer14.price);
        System.out.println("Blazzer 14 isWoolen: " + blazzer14.isWoolen);
        System.out.println("Blazzer 14 isAvailable: " + blazzer14.isAvailable);

        Blazzer blazzer15 = new Blazzer();
        blazzer15.blazzerId = 15;
        blazzer15.brand = "Lacoste";
        blazzer15.size = "M";
        blazzer15.color = "Charcoal";
        blazzer15.price = 5599.99;
        blazzer15.isWoolen = true;
        blazzer15.isAvailable = true;
        System.out.println("Blazzer 15 ID: " + blazzer15.blazzerId);
        System.out.println("Blazzer 15 Brand: " + blazzer15.brand);
        System.out.println("Blazzer 15 Size: " + blazzer15.size);
        System.out.println("Blazzer 15 Color: " + blazzer15.color);
        System.out.println("Blazzer 15 Price: " + blazzer15.price);
        System.out.println("Blazzer 15 isWoolen: " + blazzer15.isWoolen);
        System.out.println("Blazzer 15 isAvailable: " + blazzer15.isAvailable);

        Blazzer blazzer16 = new Blazzer();
        blazzer16.blazzerId = 16;
        blazzer16.brand = "Indian Terrain";
        blazzer16.size = "L";
        blazzer16.color = "Red";
        blazzer16.price = 3899.10;
        blazzer16.isWoolen = false;
        blazzer16.isAvailable = true;
        System.out.println("Blazzer 16 ID: " + blazzer16.blazzerId);
        System.out.println("Blazzer 16 Brand: " + blazzer16.brand);
        System.out.println("Blazzer 16 Size: " + blazzer16.size);
        System.out.println("Blazzer 16 Color: " + blazzer16.color);
        System.out.println("Blazzer 16 Price: " + blazzer16.price);
        System.out.println("Blazzer 16 isWoolen: " + blazzer16.isWoolen);
        System.out.println("Blazzer 16 isAvailable: " + blazzer16.isAvailable);

        Blazzer blazzer17 = new Blazzer();
        blazzer17.blazzerId = 17;
        blazzer17.brand = "GAP";
        blazzer17.size = "S";
        blazzer17.color = "Wine";
        blazzer17.price = 4699.60;
        blazzer17.isWoolen = true;
        blazzer17.isAvailable = false;
        System.out.println("Blazzer 17 ID: " + blazzer17.blazzerId);
        System.out.println("Blazzer 17 Brand: " + blazzer17.brand);
        System.out.println("Blazzer 17 Size: " + blazzer17.size);
        System.out.println("Blazzer 17 Color: " + blazzer17.color);
        System.out.println("Blazzer 17 Price: " + blazzer17.price);
        System.out.println("Blazzer 17 isWoolen: " + blazzer17.isWoolen);
        System.out.println("Blazzer 17 isAvailable: " + blazzer17.isAvailable);

        Blazzer blazzer18 = new Blazzer();
        blazzer18.blazzerId = 18;
        blazzer18.brand = "Puma";
        blazzer18.size = "XL";
        blazzer18.color = "Dark Green";
        blazzer18.price = 4799.25;
        blazzer18.isWoolen = false;
        blazzer18.isAvailable = true;
        System.out.println("Blazzer 18 ID: " + blazzer18.blazzerId);
        System.out.println("Blazzer 18 Brand: " + blazzer18.brand);
        System.out.println("Blazzer 18 Size: " + blazzer18.size);
        System.out.println("Blazzer 18 Color: " + blazzer18.color);
        System.out.println("Blazzer 18 Price: " + blazzer18.price);
        System.out.println("Blazzer 18 isWoolen: " + blazzer18.isWoolen);
        System.out.println("Blazzer 18 isAvailable: " + blazzer18.isAvailable);

        Blazzer blazzer19 = new Blazzer();
        blazzer19.blazzerId = 19;
        blazzer19.brand = "U.S. Polo Assn.";
        blazzer19.size = "L";
        blazzer19.color = "Sky Blue";
        blazzer19.price = 3890.40;
        blazzer19.isWoolen = true;
        blazzer19.isAvailable = true;
        System.out.println("Blazzer 19 ID: " + blazzer19.blazzerId);
        System.out.println("Blazzer 19 Brand: " + blazzer19.brand);
        System.out.println("Blazzer 19 Size: " + blazzer19.size);
        System.out.println("Blazzer 19 Color: " + blazzer19.color);
        System.out.println("Blazzer 19 Price: " + blazzer19.price);
        System.out.println("Blazzer 19 isWoolen: " + blazzer19.isWoolen);
        System.out.println("Blazzer 19 isAvailable: " + blazzer19.isAvailable);

        Blazzer blazzer20 = new Blazzer();
        blazzer20.blazzerId = 20;
        blazzer20.brand = "Reebok";
        blazzer20.size = "M";
        blazzer20.color = "Jet Black";
        blazzer20.price = 4999.99;
        blazzer20.isWoolen = true;
        blazzer20.isAvailable = false;
        System.out.println("Blazzer 20 ID: " + blazzer20.blazzerId);
        System.out.println("Blazzer 20 Brand: " + blazzer20.brand);
        System.out.println("Blazzer 20 Size: " + blazzer20.size);
        System.out.println("Blazzer 20 Color: " + blazzer20.color);
        System.out.println("Blazzer 20 Price: " + blazzer20.price);
        System.out.println("Blazzer 20 isWoolen: " + blazzer20.isWoolen);
        System.out.println("Blazzer 20 isAvailable: " + blazzer20.isAvailable);

        System.out.println("main ended");
    }
}


