class CoinsRunner {
    public static void main(String[] args) {
        System.out.println("main started");

        Coins coin1 = new Coins();
        coin1.coinId = 1;
        coin1.country = "India";
        coin1.value = 1.0;
        coin1.material = "Steel";
        coin1.year = 2000;
        coin1.isRare = false;
        System.out.println("Coin ID: " + coin1.coinId);
        System.out.println("Country: " + coin1.country);
        System.out.println("Value: " + coin1.value);
        System.out.println("Material: " + coin1.material);
        System.out.println("Year: " + coin1.year);
        System.out.println("Is Rare: " + coin1.isRare);

        Coins coin2 = new Coins();
        coin2.coinId = 2;
        coin2.country = "USA";
        coin2.value = 0.25;
        coin2.material = "Nickel";
        coin2.year = 1998;
        coin2.isRare = true;
        System.out.println("Coin ID: " + coin2.coinId);
        System.out.println("Country: " + coin2.country);
        System.out.println("Value: " + coin2.value);
        System.out.println("Material: " + coin2.material);
        System.out.println("Year: " + coin2.year);
        System.out.println("Is Rare: " + coin2.isRare);

        Coins coin3 = new Coins();
        coin3.coinId = 3;
        coin3.country = "UK";
        coin3.value = 0.5;
        coin3.material = "Copper-Nickel";
        coin3.year = 1982;
        coin3.isRare = false;
        System.out.println("Coin ID: " + coin3.coinId);
        System.out.println("Country: " + coin3.country);
        System.out.println("Value: " + coin3.value);
        System.out.println("Material: " + coin3.material);
        System.out.println("Year: " + coin3.year);
        System.out.println("Is Rare: " + coin3.isRare);

        Coins coin4 = new Coins();
        coin4.coinId = 4;
        coin4.country = "Canada";
        coin4.value = 2.0;
        coin4.material = "Bimetallic";
        coin4.year = 2005;
        coin4.isRare = true;
        System.out.println("Coin ID: " + coin4.coinId);
        System.out.println("Country: " + coin4.country);
        System.out.println("Value: " + coin4.value);
        System.out.println("Material: " + coin4.material);
        System.out.println("Year: " + coin4.year);
        System.out.println("Is Rare: " + coin4.isRare);

        Coins coin5 = new Coins();
        coin5.coinId = 5;
        coin5.country = "Japan";
        coin5.value = 10;
        coin5.material = "Bronze";
        coin5.year = 1970;
        coin5.isRare = false;
        System.out.println("Coin ID: " + coin5.coinId);
        System.out.println("Country: " + coin5.country);
        System.out.println("Value: " + coin5.value);
        System.out.println("Material: " + coin5.material);
        System.out.println("Year: " + coin5.year);
        System.out.println("Is Rare: " + coin5.isRare);

        Coins coin6 = new Coins();
        coin6.coinId = 6;
        coin6.country = "Germany";
        coin6.value = 1;
        coin6.material = "Aluminum";
        coin6.year = 1995;
        coin6.isRare = true;
        System.out.println("Coin ID: " + coin6.coinId);
        System.out.println("Country: " + coin6.country);
        System.out.println("Value: " + coin6.value);
        System.out.println("Material: " + coin6.material);
        System.out.println("Year: " + coin6.year);
        System.out.println("Is Rare: " + coin6.isRare);

        Coins coin7 = new Coins();
        coin7.coinId = 7;
        coin7.country = "France";
        coin7.value = 5;
        coin7.material = "Brass";
        coin7.year = 1965;
        coin7.isRare = true;
        System.out.println("Coin ID: " + coin7.coinId);
        System.out.println("Country: " + coin7.country);
        System.out.println("Value: " + coin7.value);
        System.out.println("Material: " + coin7.material);
        System.out.println("Year: " + coin7.year);
        System.out.println("Is Rare: " + coin7.isRare);

        Coins coin8 = new Coins();
        coin8.coinId = 8;
        coin8.country = "Russia";
        coin8.value = 1;
        coin8.material = "Zinc";
        coin8.year = 2001;
        coin8.isRare = false;
        System.out.println("Coin ID: " + coin8.coinId);
        System.out.println("Country: " + coin8.country);
        System.out.println("Value: " + coin8.value);
        System.out.println("Material: " + coin8.material);
        System.out.println("Year: " + coin8.year);
        System.out.println("Is Rare: " + coin8.isRare);

        Coins coin9 = new Coins();
        coin9.coinId = 9;
        coin9.country = "Italy";
        coin9.value = 2;
        coin9.material = "Steel";
        coin9.year = 1989;
        coin9.isRare = false;
        System.out.println("Coin ID: " + coin9.coinId);
        System.out.println("Country: " + coin9.country);
        System.out.println("Value: " + coin9.value);
        System.out.println("Material: " + coin9.material);
        System.out.println("Year: " + coin9.year);
        System.out.println("Is Rare: " + coin9.isRare);

        Coins coin10 = new Coins();
        coin10.coinId = 10;
        coin10.country = "China";
        coin10.value = 1;
        coin10.material = "Copper";
        coin10.year = 2003;
        coin10.isRare = false;
        System.out.println("Coin ID: " + coin10.coinId);
        System.out.println("Country: " + coin10.country);
        System.out.println("Value: " + coin10.value);
        System.out.println("Material: " + coin10.material);
        System.out.println("Year: " + coin10.year);
        System.out.println("Is Rare: " + coin10.isRare);

             Coins coin11 = new Coins();
        coin11.coinId = 11;
        coin11.country = "Australia";
        coin11.value = 0.5;
        coin11.material = "Aluminum-Bronze";
        coin11.year = 1999;
        coin11.isRare = true;
        System.out.println("Coin ID: " + coin11.coinId);
        System.out.println("Country: " + coin11.country);
        System.out.println("Value: " + coin11.value);
        System.out.println("Material: " + coin11.material);
        System.out.println("Year: " + coin11.year);
        System.out.println("Is Rare: " + coin11.isRare);

        Coins coin12 = new Coins();
        coin12.coinId = 12;
        coin12.country = "Mexico";
        coin12.value = 5;
        coin12.material = "Copper";
        coin12.year = 1990;
        coin12.isRare = false;
        System.out.println("Coin ID: " + coin12.coinId);
        System.out.println("Country: " + coin12.country);
        System.out.println("Value: " + coin12.value);
        System.out.println("Material: " + coin12.material);
        System.out.println("Year: " + coin12.year);
        System.out.println("Is Rare: " + coin12.isRare);

        Coins coin13 = new Coins();
        coin13.coinId = 13;
        coin13.country = "South Korea";
        coin13.value = 10;
        coin13.material = "Zinc";
        coin13.year = 2008;
        coin13.isRare = false;
        System.out.println("Coin ID: " + coin13.coinId);
        System.out.println("Country: " + coin13.country);
        System.out.println("Value: " + coin13.value);
        System.out.println("Material: " + coin13.material);
        System.out.println("Year: " + coin13.year);
        System.out.println("Is Rare: " + coin13.isRare);

        Coins coin14 = new Coins();
        coin14.coinId = 14;
        coin14.country = "Brazil";
        coin14.value = 1;
        coin14.material = "Nickel";
        coin14.year = 2006;
        coin14.isRare = true;
        System.out.println("Coin ID: " + coin14.coinId);
        System.out.println("Country: " + coin14.country);
        System.out.println("Value: " + coin14.value);
        System.out.println("Material: " + coin14.material);
        System.out.println("Year: " + coin14.year);
        System.out.println("Is Rare: " + coin14.isRare);

        Coins coin15 = new Coins();
        coin15.coinId = 15;
        coin15.country = "Argentina";
        coin15.value = 2;
        coin15.material = "Brass";
        coin15.year = 1992;
        coin15.isRare = false;
        System.out.println("Coin ID: " + coin15.coinId);
        System.out.println("Country: " + coin15.country);
        System.out.println("Value: " + coin15.value);
        System.out.println("Material: " + coin15.material);
        System.out.println("Year: " + coin15.year);
        System.out.println("Is Rare: " + coin15.isRare);

        Coins coin16 = new Coins();
        coin16.coinId = 16;
        coin16.country = "Egypt";
        coin16.value = 1;
        coin16.material = "Gold-Plated";
        coin16.year = 2000;
        coin16.isRare = true;
        System.out.println("Coin ID: " + coin16.coinId);
        System.out.println("Country: " + coin16.country);
        System.out.println("Value: " + coin16.value);
        System.out.println("Material: " + coin16.material);
        System.out.println("Year: " + coin16.year);
        System.out.println("Is Rare: " + coin16.isRare);

        Coins coin17 = new Coins();
        coin17.coinId = 17;
        coin17.country = "Nepal";
        coin17.value = 5;
        coin17.material = "Steel";
        coin17.year = 2015;
        coin17.isRare = false;
        System.out.println("Coin ID: " + coin17.coinId);
        System.out.println("Country: " + coin17.country);
        System.out.println("Value: " + coin17.value);
        System.out.println("Material: " + coin17.material);
        System.out.println("Year: " + coin17.year);
        System.out.println("Is Rare: " + coin17.isRare);

        Coins coin18 = new Coins();
        coin18.coinId = 18;
        coin18.country = "Bhutan";
        coin18.value = 10;
        coin18.material = "Bronze";
        coin18.year = 2012;
        coin18.isRare = true;
        System.out.println("Coin ID: " + coin18.coinId);
        System.out.println("Country: " + coin18.country);
        System.out.println("Value: " + coin18.value);
        System.out.println("Material: " + coin18.material);
        System.out.println("Year: " + coin18.year);
        System.out.println("Is Rare: " + coin18.isRare);

        Coins coin19 = new Coins();
        coin19.coinId = 19;
        coin19.country = "Thailand";
        coin19.value = 2;
        coin19.material = "Steel";
        coin19.year = 2009;
        coin19.isRare = false;
        System.out.println("Coin ID: " + coin19.coinId);
        System.out.println("Country: " + coin19.country);
        System.out.println("Value: " + coin19.value);
        System.out.println("Material: " + coin19.material);
        System.out.println("Year: " + coin19.year);
        System.out.println("Is Rare: " + coin19.isRare);

        Coins coin20 = new Coins();
        coin20.coinId = 20;
        coin20.country = "Sri Lanka";
        coin20.value = 5;
        coin20.material = "Nickel";
        coin20.year = 2010;
        coin20.isRare = true;
        System.out.println("Coin ID: " + coin20.coinId);
        System.out.println("Country: " + coin20.country);
        System.out.println("Value: " + coin20.value);
        System.out.println("Material: " + coin20.material);
        System.out.println("Year: " + coin20.year);
        System.out.println("Is Rare: " + coin20.isRare);

        System.out.println("main ended");
    }
}

