public class GymEquipmentRunner {
    public static void main(String[] args) {
        System.out.println("main started");

        GymEquipment eq1 = new GymEquipment();
        eq1.equipmentId = 1;
        eq1.name = "Treadmill";
        eq1.price = 45000.0;
        eq1.brand = "FitPro";
        eq1.weight = 70.5;
        eq1.isElectronic = true;
        System.out.println("Equipment 1 ID: " + eq1.equipmentId);
        System.out.println("Name: " + eq1.name);
        System.out.println("Price: " + eq1.price);
        System.out.println("Brand: " + eq1.brand);
        System.out.println("Weight: " + eq1.weight);
        System.out.println("Electronic: " + eq1.isElectronic);

        GymEquipment eq2 = new GymEquipment();
        eq2.equipmentId = 2;
        eq2.name = "Dumbbells";
        eq2.price = 1500.0;
        eq2.brand = "MuscleBlaze";
        eq2.weight = 10.0;
        eq2.isElectronic = false;
        System.out.println("Equipment 2 ID: " + eq2.equipmentId);
        System.out.println("Name: " + eq2.name);
        System.out.println("Price: " + eq2.price);
        System.out.println("Brand: " + eq2.brand);
        System.out.println("Weight: " + eq2.weight);
        System.out.println("Electronic: " + eq2.isElectronic);

        GymEquipment eq3 = new GymEquipment();
        eq3.equipmentId = 3;
        eq3.name = "Exercise Bike";
        eq3.price = 22000.0;
        eq3.brand = "CycloFit";
        eq3.weight = 55.0;
        eq3.isElectronic = true;
        System.out.println("Equipment 3 ID: " + eq3.equipmentId);
        System.out.println("Name: " + eq3.name);
        System.out.println("Price: " + eq3.price);
        System.out.println("Brand: " + eq3.brand);
        System.out.println("Weight: " + eq3.weight);
        System.out.println("Electronic: " + eq3.isElectronic);

        GymEquipment eq4 = new GymEquipment();
        eq4.equipmentId = 4;
        eq4.name = "Bench Press";
        eq4.price = 12000.0;
        eq4.brand = "ProGym";
        eq4.weight = 80.0;
        eq4.isElectronic = false;
        System.out.println("Equipment 4 ID: " + eq4.equipmentId);
        System.out.println("Name: " + eq4.name);
        System.out.println("Price: " + eq4.price);
        System.out.println("Brand: " + eq4.brand);
        System.out.println("Weight: " + eq4.weight);
        System.out.println("Electronic: " + eq4.isElectronic);

        GymEquipment eq5 = new GymEquipment();
        eq5.equipmentId = 5;
        eq5.name = "Elliptical Trainer";
        eq5.price = 30000.0;
        eq5.brand = "OrbitX";
        eq5.weight = 65.0;
        eq5.isElectronic = true;
        System.out.println("Equipment 5 ID: " + eq5.equipmentId);
        System.out.println("Name: " + eq5.name);
        System.out.println("Price: " + eq5.price);
        System.out.println("Brand: " + eq5.brand);
        System.out.println("Weight: " + eq5.weight);
        System.out.println("Electronic: " + eq5.isElectronic);

        GymEquipment eq6 = new GymEquipment();
        eq6.equipmentId = 6;
        eq6.name = "Rowing Machine";
        eq6.price = 35000.0;
        eq6.brand = "AquaRow";
        eq6.weight = 72.0;
        eq6.isElectronic = true;
        System.out.println("Equipment 6 ID: " + eq6.equipmentId);
        System.out.println("Name: " + eq6.name);
        System.out.println("Price: " + eq6.price);
        System.out.println("Brand: " + eq6.brand);
        System.out.println("Weight: " + eq6.weight);
        System.out.println("Electronic: " + eq6.isElectronic);

        GymEquipment eq7 = new GymEquipment();
        eq7.equipmentId = 7;
        eq7.name = "Kettlebell";
        eq7.price = 899.0;
        eq7.brand = "IronFit";
        eq7.weight = 12.0;
        eq7.isElectronic = false;
        System.out.println("Equipment 7 ID: " + eq7.equipmentId);
        System.out.println("Name: " + eq7.name);
        System.out.println("Price: " + eq7.price);
        System.out.println("Brand: " + eq7.brand);
        System.out.println("Weight: " + eq7.weight);
        System.out.println("Electronic: " + eq7.isElectronic);

        GymEquipment eq8 = new GymEquipment();
        eq8.equipmentId = 8;
        eq8.name = "Resistance Band";
        eq8.price = 299.0;
        eq8.brand = "FlexiBands";
        eq8.weight = 1.5;
        eq8.isElectronic = false;
        System.out.println("Equipment 8 ID: " + eq8.equipmentId);
        System.out.println("Name: " + eq8.name);
        System.out.println("Price: " + eq8.price);
        System.out.println("Brand: " + eq8.brand);
        System.out.println("Weight: " + eq8.weight);
        System.out.println("Electronic: " + eq8.isElectronic);

        GymEquipment eq9 = new GymEquipment();
        eq9.equipmentId = 9;
        eq9.name = "Leg Press Machine";
        eq9.price = 38000.0;
        eq9.brand = "PowerMax";
        eq9.weight = 100.0;
        eq9.isElectronic = false;
        System.out.println("Equipment 9 ID: " + eq9.equipmentId);
        System.out.println("Name: " + eq9.name);
        System.out.println("Price: " + eq9.price);
        System.out.println("Brand: " + eq9.brand);
        System.out.println("Weight: " + eq9.weight);
        System.out.println("Electronic: " + eq9.isElectronic);

        GymEquipment eq10 = new GymEquipment();
        eq10.equipmentId = 10;
        eq10.name = "Lat Pulldown";
        eq10.price = 15000.0;
        eq10.brand = "BodyBoss";
        eq10.weight = 60.0;
        eq10.isElectronic = false;
        System.out.println("Equipment 10 ID: " + eq10.equipmentId);
        System.out.println("Name: " + eq10.name);
        System.out.println("Price: " + eq10.price);
        System.out.println("Brand: " + eq10.brand);
        System.out.println("Weight: " + eq10.weight);
        System.out.println("Electronic: " + eq10.isElectronic);

            GymEquipment eq11 = new GymEquipment();
        eq11.equipmentId = 11;
        eq11.name = "Smith Machine";
        eq11.price = 45000.0;
        eq11.brand = "GymStar";
        eq11.weight = 110.0;
        eq11.isElectronic = false;
        System.out.println("Equipment 11 ID: " + eq11.equipmentId);
        System.out.println("Name: " + eq11.name);
        System.out.println("Price: " + eq11.price);
        System.out.println("Brand: " + eq11.brand);
        System.out.println("Weight: " + eq11.weight);
        System.out.println("Electronic: " + eq11.isElectronic);

        GymEquipment eq12 = new GymEquipment();
        eq12.equipmentId = 12;
        eq12.name = "Power Rack";
        eq12.price = 40000.0;
        eq12.brand = "SteelCore";
        eq12.weight = 120.0;
        eq12.isElectronic = false;
        System.out.println("Equipment 12 ID: " + eq12.equipmentId);
        System.out.println("Name: " + eq12.name);
        System.out.println("Price: " + eq12.price);
        System.out.println("Brand: " + eq12.brand);
        System.out.println("Weight: " + eq12.weight);
        System.out.println("Electronic: " + eq12.isElectronic);

        GymEquipment eq13 = new GymEquipment();
        eq13.equipmentId = 13;
        eq13.name = "Vibration Plate";
        eq13.price = 8500.0;
        eq13.brand = "VibraFit";
        eq13.weight = 40.0;
        eq13.isElectronic = true;
        System.out.println("Equipment 13 ID: " + eq13.equipmentId);
        System.out.println("Name: " + eq13.name);
        System.out.println("Price: " + eq13.price);
        System.out.println("Brand: " + eq13.brand);
        System.out.println("Weight: " + eq13.weight);
        System.out.println("Electronic: " + eq13.isElectronic);

        GymEquipment eq14 = new GymEquipment();
        eq14.equipmentId = 14;
        eq14.name = "Pull-Up Bar";
        eq14.price = 2500.0;
        eq14.brand = "WallFit";
        eq14.weight = 15.0;
        eq14.isElectronic = false;
        System.out.println("Equipment 14 ID: " + eq14.equipmentId);
        System.out.println("Name: " + eq14.name);
        System.out.println("Price: " + eq14.price);
        System.out.println("Brand: " + eq14.brand);
        System.out.println("Weight: " + eq14.weight);
        System.out.println("Electronic: " + eq14.isElectronic);

        GymEquipment eq15 = new GymEquipment();
        eq15.equipmentId = 15;
        eq15.name = "Stepper";
        eq15.price = 9800.0;
        eq15.brand = "ClimbFit";
        eq15.weight = 33.0;
        eq15.isElectronic = true;
        System.out.println("Equipment 15 ID: " + eq15.equipmentId);
        System.out.println("Name: " + eq15.name);
        System.out.println("Price: " + eq15.price);
        System.out.println("Brand: " + eq15.brand);
        System.out.println("Weight: " + eq15.weight);
        System.out.println("Electronic: " + eq15.isElectronic);

        GymEquipment eq16 = new GymEquipment();
        eq16.equipmentId = 16;
        eq16.name = "Punching Bag";
        eq16.price = 3500.0;
        eq16.brand = "FightPro";
        eq16.weight = 25.0;
        eq16.isElectronic = false;
        System.out.println("Equipment 16 ID: " + eq16.equipmentId);
        System.out.println("Name: " + eq16.name);
        System.out.println("Price: " + eq16.price);
        System.out.println("Brand: " + eq16.brand);
        System.out.println("Weight: " + eq16.weight);
        System.out.println("Electronic: " + eq16.isElectronic);

        GymEquipment eq17 = new GymEquipment();
        eq17.equipmentId = 17;
        eq17.name = "Incline Bench";
        eq17.price = 7800.0;
        eq17.brand = "FlexFit";
        eq17.weight = 35.0;
        eq17.isElectronic = false;
        System.out.println("Equipment 17 ID: " + eq17.equipmentId);
        System.out.println("Name: " + eq17.name);
        System.out.println("Price: " + eq17.price);
        System.out.println("Brand: " + eq17.brand);
        System.out.println("Weight: " + eq17.weight);
        System.out.println("Electronic: " + eq17.isElectronic);

        GymEquipment eq18 = new GymEquipment();
        eq18.equipmentId = 18;
        eq18.name = "Cable Crossover";
        eq18.price = 32000.0;
        eq18.brand = "CrossoverMax";
        eq18.weight = 95.0;
        eq18.isElectronic = false;
        System.out.println("Equipment 18 ID: " + eq18.equipmentId);
        System.out.println("Name: " + eq18.name);
        System.out.println("Price: " + eq18.price);
        System.out.println("Brand: " + eq18.brand);
        System.out.println("Weight: " + eq18.weight);
        System.out.println("Electronic: " + eq18.isElectronic);

        GymEquipment eq19 = new GymEquipment();
        eq19.equipmentId = 19;
        eq19.name = "Chest Press";
        eq19.price = 16000.0;
        eq19.brand = "IronChest";
        eq19.weight = 85.0;
        eq19.isElectronic = false;
        System.out.println("Equipment 19 ID: " + eq19.equipmentId);
        System.out.println("Name: " + eq19.name);
        System.out.println("Price: " + eq19.price);
        System.out.println("Brand: " + eq19.brand);
        System.out.println("Weight: " + eq19.weight);
        System.out.println("Electronic: " + eq19.isElectronic);

        GymEquipment eq20 = new GymEquipment();
        eq20.equipmentId = 20;
        eq20.name = "Spin Bike";
        eq20.price = 21000.0;
        eq20.brand = "SpinX";
        eq20.weight = 58.0;
        eq20.isElectronic = true;
        System.out.println("Equipment 20 ID: " + eq20.equipmentId);
        System.out.println("Name: " + eq20.name);
        System.out.println("Price: " + eq20.price);
        System.out.println("Brand: " + eq20.brand);
        System.out.println("Weight: " + eq20.weight);
        System.out.println("Electronic: " + eq20.isElectronic);

        System.out.println("main ended");
    }
}

