class HatRunner {
    public static void main(String[] args) {
        System.out.println("main started");

        Hat hat1 = new Hat();
        hat1.hatId = 1;
        hat1.brand = "Adidas";
        hat1.color = "Black";
        hat1.size = "M";
        hat1.material = "Cotton";
        hat1.price = 499.99;
        System.out.println("Hat ID: " + hat1.hatId);
        System.out.println("Brand: " + hat1.brand);
        System.out.println("Color: " + hat1.color);
        System.out.println("Size: " + hat1.size);
        System.out.println("Material: " + hat1.material);
        System.out.println("Price: " + hat1.price);

        Hat hat2 = new Hat();
        hat2.hatId = 2;
        hat2.brand = "Nike";
        hat2.color = "White";
        hat2.size = "L";
        hat2.material = "Polyester";
        hat2.price = 599.00;
        System.out.println("Hat ID: " + hat2.hatId);
        System.out.println("Brand: " + hat2.brand);
        System.out.println("Color: " + hat2.color);
        System.out.println("Size: " + hat2.size);
        System.out.println("Material: " + hat2.material);
        System.out.println("Price: " + hat2.price);

        Hat hat3 = new Hat();
        hat3.hatId = 3;
        hat3.brand = "Puma";
        hat3.color = "Blue";
        hat3.size = "S";
        hat3.material = "Wool";
        hat3.price = 699.50;
        System.out.println("Hat ID: " + hat3.hatId);
        System.out.println("Brand: " + hat3.brand);
        System.out.println("Color: " + hat3.color);
        System.out.println("Size: " + hat3.size);
        System.out.println("Material: " + hat3.material);
        System.out.println("Price: " + hat3.price);

        Hat hat4 = new Hat();
        hat4.hatId = 4;
        hat4.brand = "Reebok";
        hat4.color = "Green";
        hat4.size = "M";
        hat4.material = "Canvas";
        hat4.price = 399.75;
        System.out.println("Hat ID: " + hat4.hatId);
        System.out.println("Brand: " + hat4.brand);
        System.out.println("Color: " + hat4.color);
        System.out.println("Size: " + hat4.size);
        System.out.println("Material: " + hat4.material);
        System.out.println("Price: " + hat4.price);

        Hat hat5 = new Hat();
        hat5.hatId = 5;
        hat5.brand = "Under Armour";
        hat5.color = "Red";
        hat5.size = "XL";
        hat5.material = "Synthetic";
        hat5.price = 849.00;
        System.out.println("Hat ID: " + hat5.hatId);
        System.out.println("Brand: " + hat5.brand);
        System.out.println("Color: " + hat5.color);
        System.out.println("Size: " + hat5.size);
        System.out.println("Material: " + hat5.material);
        System.out.println("Price: " + hat5.price);

               Hat hat6 = new Hat();
        hat6.hatId = 6;
        hat6.brand = "Fila";
        hat6.color = "Grey";
        hat6.size = "L";
        hat6.material = "Cotton Blend";
        hat6.price = 479.00;
        System.out.println("Hat ID: " + hat6.hatId);
        System.out.println("Brand: " + hat6.brand);
        System.out.println("Color: " + hat6.color);
        System.out.println("Size: " + hat6.size);
        System.out.println("Material: " + hat6.material);
        System.out.println("Price: " + hat6.price);

        Hat hat7 = new Hat();
        hat7.hatId = 7;
        hat7.brand = "Columbia";
        hat7.color = "Khaki";
        hat7.size = "M";
        hat7.material = "Linen";
        hat7.price = 749.50;
        System.out.println("Hat ID: " + hat7.hatId);
        System.out.println("Brand: " + hat7.brand);
        System.out.println("Color: " + hat7.color);
        System.out.println("Size: " + hat7.size);
        System.out.println("Material: " + hat7.material);
        System.out.println("Price: " + hat7.price);

        Hat hat8 = new Hat();
        hat8.hatId = 8;
        hat8.brand = "Levi's";
        hat8.color = "Brown";
        hat8.size = "S";
        hat8.material = "Denim";
        hat8.price = 699.00;
        System.out.println("Hat ID: " + hat8.hatId);
        System.out.println("Brand: " + hat8.brand);
        System.out.println("Color: " + hat8.color);
        System.out.println("Size: " + hat8.size);
        System.out.println("Material: " + hat8.material);
        System.out.println("Price: " + hat8.price);

        Hat hat9 = new Hat();
        hat9.hatId = 9;
        hat9.brand = "HRX";
        hat9.color = "Olive";
        hat9.size = "M";
        hat9.material = "Wool Blend";
        hat9.price = 639.49;
        System.out.println("Hat ID: " + hat9.hatId);
        System.out.println("Brand: " + hat9.brand);
        System.out.println("Color: " + hat9.color);
        System.out.println("Size: " + hat9.size);
        System.out.println("Material: " + hat9.material);
        System.out.println("Price: " + hat9.price);

        Hat hat10 = new Hat();
        hat10.hatId = 10;
        hat10.brand = "Wildcraft";
        hat10.color = "Orange";
        hat10.size = "XL";
        hat10.material = "Canvas";
        hat10.price = 899.99;
        System.out.println("Hat ID: " + hat10.hatId);
        System.out.println("Brand: " + hat10.brand);
        System.out.println("Color: " + hat10.color);
        System.out.println("Size: " + hat10.size);
        System.out.println("Material: " + hat10.material);
        System.out.println("Price: " + hat10.price);

        Hat hat11 = new Hat();
        hat11.hatId = 11;
        hat11.brand = "H&M";
        hat11.color = "Yellow";
        hat11.size = "M";
        hat11.material = "Synthetic";
        hat11.price = 555.00;
        System.out.println("Hat ID: " + hat11.hatId);
        System.out.println("Brand: " + hat11.brand);
        System.out.println("Color: " + hat11.color);
        System.out.println("Size: " + hat11.size);
        System.out.println("Material: " + hat11.material);
        System.out.println("Price: " + hat11.price);

        Hat hat12 = new Hat();
        hat12.hatId = 12;
        hat12.brand = "Zara";
        hat12.color = "Peach";
        hat12.size = "S";
        hat12.material = "Silk";
        hat12.price = 1050.00;
        System.out.println("Hat ID: " + hat12.hatId);
        System.out.println("Brand: " + hat12.brand);
        System.out.println("Color: " + hat12.color);
        System.out.println("Size: " + hat12.size);
        System.out.println("Material: " + hat12.material);
        System.out.println("Price: " + hat12.price);

        Hat hat13 = new Hat();
        hat13.hatId = 13;
        hat13.brand = "Gucci";
        hat13.color = "Beige";
        hat13.size = "M";
        hat13.material = "Wool";
        hat13.price = 2000.00;
        System.out.println("Hat ID: " + hat13.hatId);
        System.out.println("Brand: " + hat13.brand);
        System.out.println("Color: " + hat13.color);
        System.out.println("Size: " + hat13.size);
        System.out.println("Material: " + hat13.material);
        System.out.println("Price: " + hat13.price);

        Hat hat14 = new Hat();
        hat14.hatId = 14;
        hat14.brand = "Fastrack";
        hat14.color = "Silver";
        hat14.size = "L";
        hat14.material = "Nylon";
        hat14.price = 449.00;
        System.out.println("Hat ID: " + hat14.hatId);
        System.out.println("Brand: " + hat14.brand);
        System.out.println("Color: " + hat14.color);
        System.out.println("Size: " + hat14.size);
        System.out.println("Material: " + hat14.material);
        System.out.println("Price: " + hat14.price);

        Hat hat15 = new Hat();
        hat15.hatId = 15;
        hat15.brand = "Roadster";
        hat15.color = "Maroon";
        hat15.size = "M";
        hat15.material = "Cotton";
        hat15.price = 599.00;
        System.out.println("Hat ID: " + hat15.hatId);
        System.out.println("Brand: " + hat15.brand);
        System.out.println("Color: " + hat15.color);
        System.out.println("Size: " + hat15.size);
        System.out.println("Material: " + hat15.material);
        System.out.println("Price: " + hat15.price);

        Hat hat16 = new Hat();
        hat16.hatId = 16;
        hat16.brand = "Biba";
        hat16.color = "Pink";
        hat16.size = "S";
        hat16.material = "Linen";
        hat16.price = 699.00;
        System.out.println("Hat ID: " + hat16.hatId);
        System.out.println("Brand: " + hat16.brand);
        System.out.println("Color: " + hat16.color);
        System.out.println("Size: " + hat16.size);
        System.out.println("Material: " + hat16.material);
        System.out.println("Price: " + hat16.price);

        Hat hat17 = new Hat();
        hat17.hatId = 17;
        hat17.brand = "Mufti";
        hat17.color = "Indigo";
        hat17.size = "XL";
        hat17.material = "Cotton";
        hat17.price = 789.50;
        System.out.println("Hat ID: " + hat17.hatId);
        System.out.println("Brand: " + hat17.brand);
        System.out.println("Color: " + hat17.color);
        System.out.println("Size: " + hat17.size);
        System.out.println("Material: " + hat17.material);
        System.out.println("Price: " + hat17.price);

        Hat hat18 = new Hat();
        hat18.hatId = 18;
        hat18.brand = "Jack & Jones";
        hat18.color = "Lavender";
        hat18.size = "L";
        hat18.material = "Denim";
        hat18.price = 899.00;
        System.out.println("Hat ID: " + hat18.hatId);
        System.out.println("Brand: " + hat18.brand);
        System.out.println("Color: " + hat18.color);
        System.out.println("Size: " + hat18.size);
        System.out.println("Material: " + hat18.material);
        System.out.println("Price: " + hat18.price);

        Hat hat19 = new Hat();
        hat19.hatId = 19;
        hat19.brand = "Allen Solly";
        hat19.color = "White";
        hat19.size = "M";
        hat19.material = "Wool Blend";
        hat19.price = 999.00;
        System.out.println("Hat ID: " + hat19.hatId);
        System.out.println("Brand: " + hat19.brand);
        System.out.println("Color: " + hat19.color);
        System.out.println("Size: " + hat19.size);
        System.out.println("Material: " + hat19.material);
        System.out.println("Price: " + hat19.price);

        Hat hat20 = new Hat();
        hat20.hatId = 20;
        hat20.brand = "Peter England";
        hat20.color = "Sky Blue";
        hat20.size = "S";
        hat20.material = "Linen Blend";
        hat20.price = 799.90;
        System.out.println("Hat ID: " + hat20.hatId);
        System.out.println("Brand: " + hat20.brand);
        System.out.println("Color: " + hat20.color);
        System.out.println("Size: " + hat20.size);
        System.out.println("Material: " + hat20.material);
        System.out.println("Price: " + hat20.price);

        System.out.println("main ended");
   

    }
}
