class InvitationCardRunner {
    public static void main(String[] args) {
        System.out.println("main started");

        InvitationCard card1 = new InvitationCard();
        card1.cardId = 1;
        card1.eventType = "Wedding";
        card1.recipientName = "John";
        card1.venue = "Sunshine Hall";
        card1.date = "20-Aug-2025";
        card1.isDigital = false;
        System.out.println("Card ID: " + card1.cardId);
        System.out.println("Event Type: " + card1.eventType);
        System.out.println("Recipient: " + card1.recipientName);
        System.out.println("Venue: " + card1.venue);
        System.out.println("Date: " + card1.date);
        System.out.println("Is Digital: " + card1.isDigital);

        InvitationCard card2 = new InvitationCard();
        card2.cardId = 2;
        card2.eventType = "Birthday";
        card2.recipientName = "Emily";
        card2.venue = "Garden Villa";
        card2.date = "15-Sep-2025";
        card2.isDigital = true;
        System.out.println("Card ID: " + card2.cardId);
        System.out.println("Event Type: " + card2.eventType);
        System.out.println("Recipient: " + card2.recipientName);
        System.out.println("Venue: " + card2.venue);
        System.out.println("Date: " + card2.date);
        System.out.println("Is Digital: " + card2.isDigital);

        InvitationCard card3 = new InvitationCard();
        card3.cardId = 3;
        card3.eventType = "Anniversary";
        card3.recipientName = "Sarah";
        card3.venue = "Crystal Palace";
        card3.date = "12-Oct-2025";
        card3.isDigital = false;
        System.out.println("Card ID: " + card3.cardId);
        System.out.println("Event Type: " + card3.eventType);
        System.out.println("Recipient: " + card3.recipientName);
        System.out.println("Venue: " + card3.venue);
        System.out.println("Date: " + card3.date);
        System.out.println("Is Digital: " + card3.isDigital);

        InvitationCard card4 = new InvitationCard();
        card4.cardId = 4;
        card4.eventType = "Housewarming";
        card4.recipientName = "David";
        card4.venue = "Maple Street Home";
        card4.date = "05-Nov-2025";
        card4.isDigital = true;
        System.out.println("Card ID: " + card4.cardId);
        System.out.println("Event Type: " + card4.eventType);
        System.out.println("Recipient: " + card4.recipientName);
        System.out.println("Venue: " + card4.venue);
        System.out.println("Date: " + card4.date);
        System.out.println("Is Digital: " + card4.isDigital);

        InvitationCard card5 = new InvitationCard();
        card5.cardId = 5;
        card5.eventType = "Baby Shower";
        card5.recipientName = "Nina";
        card5.venue = "Palm Resort";
        card5.date = "10-Dec-2025";
        card5.isDigital = false;
        System.out.println("Card ID: " + card5.cardId);
        System.out.println("Event Type: " + card5.eventType);
        System.out.println("Recipient: " + card5.recipientName);
        System.out.println("Venue: " + card5.venue);
        System.out.println("Date: " + card5.date);
        System.out.println("Is Digital: " + card5.isDigital);

             InvitationCard card6 = new InvitationCard();
        card6.cardId = 6;
        card6.eventType = "Engagement";
        card6.recipientName = "Alex";
        card6.venue = "Grand Pavilion";
        card6.date = "22-Jan-2026";
        card6.isDigital = true;
        System.out.println("Card ID: " + card6.cardId);
        System.out.println("Event Type: " + card6.eventType);
        System.out.println("Recipient: " + card6.recipientName);
        System.out.println("Venue: " + card6.venue);
        System.out.println("Date: " + card6.date);
        System.out.println("Is Digital: " + card6.isDigital);

        InvitationCard card7 = new InvitationCard();
        card7.cardId = 7;
        card7.eventType = "Graduation";
        card7.recipientName = "Liam";
        card7.venue = "University Hall";
        card7.date = "05-Feb-2026";
        card7.isDigital = false;
        System.out.println("Card ID: " + card7.cardId);
        System.out.println("Event Type: " + card7.eventType);
        System.out.println("Recipient: " + card7.recipientName);
        System.out.println("Venue: " + card7.venue);
        System.out.println("Date: " + card7.date);
        System.out.println("Is Digital: " + card7.isDigital);

        InvitationCard card8 = new InvitationCard();
        card8.cardId = 8;
        card8.eventType = "Reception";
        card8.recipientName = "Olivia";
        card8.venue = "Royal Orchid";
        card8.date = "12-Feb-2026";
        card8.isDigital = true;
        System.out.println("Card ID: " + card8.cardId);
        System.out.println("Event Type: " + card8.eventType);
        System.out.println("Recipient: " + card8.recipientName);
        System.out.println("Venue: " + card8.venue);
        System.out.println("Date: " + card8.date);
        System.out.println("Is Digital: " + card8.isDigital);

        InvitationCard card9 = new InvitationCard();
        card9.cardId = 9;
        card9.eventType = "Baby Naming";
        card9.recipientName = "Ethan";
        card9.venue = "Skyview Club";
        card9.date = "18-Feb-2026";
        card9.isDigital = false;
        System.out.println("Card ID: " + card9.cardId);
        System.out.println("Event Type: " + card9.eventType);
        System.out.println("Recipient: " + card9.recipientName);
        System.out.println("Venue: " + card9.venue);
        System.out.println("Date: " + card9.date);
        System.out.println("Is Digital: " + card9.isDigital);

        InvitationCard card10 = new InvitationCard();
        card10.cardId = 10;
        card10.eventType = "Retirement";
        card10.recipientName = "Grace";
        card10.venue = "Heritage Club";
        card10.date = "25-Feb-2026";
        card10.isDigital = true;
        System.out.println("Card ID: " + card10.cardId);
        System.out.println("Event Type: " + card10.eventType);
        System.out.println("Recipient: " + card10.recipientName);
        System.out.println("Venue: " + card10.venue);
        System.out.println("Date: " + card10.date);
        System.out.println("Is Digital: " + card10.isDigital);

        InvitationCard card11 = new InvitationCard();
        card11.cardId = 11;
        card11.eventType = "Inauguration";
        card11.recipientName = "Mia";
        card11.venue = "Phoenix Tower";
        card11.date = "01-Mar-2026";
        card11.isDigital = false;
        System.out.println("Card ID: " + card11.cardId);
        System.out.println("Event Type: " + card11.eventType);
        System.out.println("Recipient: " + card11.recipientName);
        System.out.println("Venue: " + card11.venue);
        System.out.println("Date: " + card11.date);
        System.out.println("Is Digital: " + card11.isDigital);

        InvitationCard card12 = new InvitationCard();
        card12.cardId = 12;
        card12.eventType = "Religious Ceremony";
        card12.recipientName = "Zara";
        card12.venue = "Holy Grace Temple";
        card12.date = "10-Mar-2026";
        card12.isDigital = true;
        System.out.println("Card ID: " + card12.cardId);
        System.out.println("Event Type: " + card12.eventType);
        System.out.println("Recipient: " + card12.recipientName);
        System.out.println("Venue: " + card12.venue);
        System.out.println("Date: " + card12.date);
        System.out.println("Is Digital: " + card12.isDigital);

        InvitationCard card13 = new InvitationCard();
        card13.cardId = 13;
        card13.eventType = "Naming Ceremony";
        card13.recipientName = "Noah";
        card13.venue = "Lotus Banquet";
        card13.date = "18-Mar-2026";
        card13.isDigital = false;
        System.out.println("Card ID: " + card13.cardId);
        System.out.println("Event Type: " + card13.eventType);
        System.out.println("Recipient: " + card13.recipientName);
        System.out.println("Venue: " + card13.venue);
        System.out.println("Date: " + card13.date);
        System.out.println("Is Digital: " + card13.isDigital);

        InvitationCard card14 = new InvitationCard();
        card14.cardId = 14;
        card14.eventType = "Graduation";
        card14.recipientName = "Sophia";
        card14.venue = "New Horizon Auditorium";
        card14.date = "25-Mar-2026";
        card14.isDigital = true;
        System.out.println("Card ID: " + card14.cardId);
        System.out.println("Event Type: " + card14.eventType);
        System.out.println("Recipient: " + card14.recipientName);
        System.out.println("Venue: " + card14.venue);
        System.out.println("Date: " + card14.date);
        System.out.println("Is Digital: " + card14.isDigital);

        InvitationCard card15 = new InvitationCard();
        card15.cardId = 15;
        card15.eventType = "Farewell";
        card15.recipientName = "Arjun";
        card15.venue = "Sky Lounge";
        card15.date = "30-Mar-2026";
        card15.isDigital = false;
        System.out.println("Card ID: " + card15.cardId);
        System.out.println("Event Type: " + card15.eventType);
        System.out.println("Recipient: " + card15.recipientName);
        System.out.println("Venue: " + card15.venue);
        System.out.println("Date: " + card15.date);
        System.out.println("Is Digital: " + card15.isDigital);

        InvitationCard card16 = new InvitationCard();
        card16.cardId = 16;
        card16.eventType = "Promotion Party";
        card16.recipientName = "Nikhil";
        card16.venue = "Coral Lounge";
        card16.date = "03-Apr-2026";
        card16.isDigital = true;
        System.out.println("Card ID: " + card16.cardId);
        System.out.println("Event Type: " + card16.eventType);
        System.out.println("Recipient: " + card16.recipientName);
        System.out.println("Venue: " + card16.venue);
        System.out.println("Date: " + card16.date);
        System.out.println("Is Digital: " + card16.isDigital);

        InvitationCard card17 = new InvitationCard();
        card17.cardId = 17;
        card17.eventType = "Cultural Fest";
        card17.recipientName = "Priya";
        card17.venue = "City Amphitheatre";
        card17.date = "07-Apr-2026";
        card17.isDigital = false;
        System.out.println("Card ID: " + card17.cardId);
        System.out.println("Event Type: " + card17.eventType);
        System.out.println("Recipient: " + card17.recipientName);
        System.out.println("Venue: " + card17.venue);
        System.out.println("Date: " + card17.date);
        System.out.println("Is Digital: " + card17.isDigital);

        InvitationCard card18 = new InvitationCard();
        card18.cardId = 18;
        card18.eventType = "Corporate Event";
        card18.recipientName = "Raj";
        card18.venue = "Taj Westend";
        card18.date = "12-Apr-2026";
        card18.isDigital = true;
        System.out.println("Card ID: " + card18.cardId);
        System.out.println("Event Type: " + card18.eventType);
        System.out.println("Recipient: " + card18.recipientName);
        System.out.println("Venue: " + card18.venue);
        System.out.println("Date: " + card18.date);
        System.out.println("Is Digital: " + card18.isDigital);

        InvitationCard card19 = new InvitationCard();
        card19.cardId = 19;
        card19.eventType = "Charity Gala";
        card19.recipientName = "Meera";
        card19.venue = "Crown Plaza";
        card19.date = "18-Apr-2026";
        card19.isDigital = false;
        System.out.println("Card ID: " + card19.cardId);
        System.out.println("Event Type: " + card19.eventType);
        System.out.println("Recipient: " + card19.recipientName);
        System.out.println("Venue: " + card19.venue);
        System.out.println("Date: " + card19.date);
        System.out.println("Is Digital: " + card19.isDigital);

        InvitationCard card20 = new InvitationCard();
        card20.cardId = 20;
        card20.eventType = "Product Launch";
        card20.recipientName = "Vikram";
        card20.venue = "Tech Convention Center";
        card20.date = "22-Apr-2026";
        card20.isDigital = true;
        System.out.println("Card ID: " + card20.cardId);
        System.out.println("Event Type: " + card20.eventType);
        System.out.println("Recipient: " + card20.recipientName);
        System.out.println("Venue: " + card20.venue);
        System.out.println("Date: " + card20.date);
        System.out.println("Is Digital: " + card20.isDigital);

        System.out.println("main ended");
  }
}
