class JwelleryRunner {
    public static void main(String[] args) {
        System.out.println("main started");

        Jwellery j1 = new Jwellery();
        j1.jwelleryId = 1;
        j1.type = "Necklace";
        j1.material = "Gold";
        j1.brand = "Tanishq";
        j1.weightInGrams = 15.2;
        j1.isHandcrafted = true;
        System.out.println("Jwellery ID: " + j1.jwelleryId);
        System.out.println("Type: " + j1.type);
        System.out.println("Material: " + j1.material);
        System.out.println("Brand: " + j1.brand);
        System.out.println("Weight: " + j1.weightInGrams);
        System.out.println("Handcrafted: " + j1.isHandcrafted);

        Jwellery j2 = new Jwellery();
        j2.jwelleryId = 2;
        j2.type = "Ring";
        j2.material = "Platinum";
        j2.brand = "Malabar";
        j2.weightInGrams = 5.3;
        j2.isHandcrafted = false;
        System.out.println("Jwellery ID: " + j2.jwelleryId);
        System.out.println("Type: " + j2.type);
        System.out.println("Material: " + j2.material);
        System.out.println("Brand: " + j2.brand);
        System.out.println("Weight: " + j2.weightInGrams);
        System.out.println("Handcrafted: " + j2.isHandcrafted);

        Jwellery j3 = new Jwellery();
        j3.jwelleryId = 3;
        j3.type = "Bracelet";
        j3.material = "Silver";
        j3.brand = "Kalyan";
        j3.weightInGrams = 12.8;
        j3.isHandcrafted = true;
        System.out.println("Jwellery ID: " + j3.jwelleryId);
        System.out.println("Type: " + j3.type);
        System.out.println("Material: " + j3.material);
        System.out.println("Brand: " + j3.brand);
        System.out.println("Weight: " + j3.weightInGrams);
        System.out.println("Handcrafted: " + j3.isHandcrafted);

        Jwellery j4 = new Jwellery();
        j4.jwelleryId = 4;
        j4.type = "Earrings";
        j4.material = "Gold";
        j4.brand = "PC Jeweller";
        j4.weightInGrams = 6.5;
        j4.isHandcrafted = false;
        System.out.println("Jwellery ID: " + j4.jwelleryId);
        System.out.println("Type: " + j4.type);
        System.out.println("Material: " + j4.material);
        System.out.println("Brand: " + j4.brand);
        System.out.println("Weight: " + j4.weightInGrams);
        System.out.println("Handcrafted: " + j4.isHandcrafted);

        Jwellery j5 = new Jwellery();
        j5.jwelleryId = 5;
        j5.type = "Anklet";
        j5.material = "Silver";
        j5.brand = "Tribes India";
        j5.weightInGrams = 18.6;
        j5.isHandcrafted = true;
        System.out.println("Jwellery ID: " + j5.jwelleryId);
        System.out.println("Type: " + j5.type);
        System.out.println("Material: " + j5.material);
        System.out.println("Brand: " + j5.brand);
        System.out.println("Weight: " + j5.weightInGrams);
        System.out.println("Handcrafted: " + j5.isHandcrafted);

        Jwellery j6 = new Jwellery();
        j6.jwelleryId = 6;
        j6.type = "Pendant";
        j6.material = "Diamond";
        j6.brand = "Caratlane";
        j6.weightInGrams = 3.4;
        j6.isHandcrafted = false;
        System.out.println("Jwellery ID: " + j6.jwelleryId);
        System.out.println("Type: " + j6.type);
        System.out.println("Material: " + j6.material);
        System.out.println("Brand: " + j6.brand);
        System.out.println("Weight: " + j6.weightInGrams);
        System.out.println("Handcrafted: " + j6.isHandcrafted);

        Jwellery j7 = new Jwellery();
        j7.jwelleryId = 7;
        j7.type = "Bangle";
        j7.material = "Gold";
        j7.brand = "Reliance Jewels";
        j7.weightInGrams = 22.1;
        j7.isHandcrafted = true;
        System.out.println("Jwellery ID: " + j7.jwelleryId);
        System.out.println("Type: " + j7.type);
        System.out.println("Material: " + j7.material);
        System.out.println("Brand: " + j7.brand);
        System.out.println("Weight: " + j7.weightInGrams);
        System.out.println("Handcrafted: " + j7.isHandcrafted);

        Jwellery j8 = new Jwellery();
        j8.jwelleryId = 8;
        j8.type = "Choker";
        j8.material = "Pearl";
        j8.brand = "BlueStone";
        j8.weightInGrams = 9.9;
        j8.isHandcrafted = true;
        System.out.println("Jwellery ID: " + j8.jwelleryId);
        System.out.println("Type: " + j8.type);
        System.out.println("Material: " + j8.material);
        System.out.println("Brand: " + j8.brand);
        System.out.println("Weight: " + j8.weightInGrams);
        System.out.println("Handcrafted: " + j8.isHandcrafted);

        Jwellery j9 = new Jwellery();
        j9.jwelleryId = 9;
        j9.type = "Toe Ring";
        j9.material = "Silver";
        j9.brand = "Amrapali";
        j9.weightInGrams = 2.5;
        j9.isHandcrafted = false;
        System.out.println("Jwellery ID: " + j9.jwelleryId);
        System.out.println("Type: " + j9.type);
        System.out.println("Material: " + j9.material);
        System.out.println("Brand: " + j9.brand);
        System.out.println("Weight: " + j9.weightInGrams);
        System.out.println("Handcrafted: " + j9.isHandcrafted);

        Jwellery j10 = new Jwellery();
        j10.jwelleryId = 10;
        j10.type = "Nose Ring";
        j10.material = "Gold";
        j10.brand = "Orra";
        j10.weightInGrams = 1.2;
        j10.isHandcrafted = true;
        System.out.println("Jwellery ID: " + j10.jwelleryId);
        System.out.println("Type: " + j10.type);
        System.out.println("Material: " + j10.material);
        System.out.println("Brand: " + j10.brand);
        System.out.println("Weight: " + j10.weightInGrams);
        System.out.println("Handcrafted: " + j10.isHandcrafted);
                Jwellery j11 = new Jwellery();
        j11.jwelleryId = 11;
        j11.type = "Maang Tikka";
        j11.material = "Gold";
        j11.brand = "Tanishq";
        j11.weightInGrams = 4.5;
        j11.isHandcrafted = false;
        System.out.println("Jwellery ID: " + j11.jwelleryId);
        System.out.println("Type: " + j11.type);
        System.out.println("Material: " + j11.material);
        System.out.println("Brand: " + j11.brand);
        System.out.println("Weight: " + j11.weightInGrams);
        System.out.println("Handcrafted: " + j11.isHandcrafted);

        Jwellery j12 = new Jwellery();
        j12.jwelleryId = 12;
        j12.type = "Cufflinks";
        j12.material = "Platinum";
        j12.brand = "BlueStone";
        j12.weightInGrams = 3.0;
        j12.isHandcrafted = true;
        System.out.println("Jwellery ID: " + j12.jwelleryId);
        System.out.println("Type: " + j12.type);
        System.out.println("Material: " + j12.material);
        System.out.println("Brand: " + j12.brand);
        System.out.println("Weight: " + j12.weightInGrams);
        System.out.println("Handcrafted: " + j12.isHandcrafted);

        Jwellery j13 = new Jwellery();
        j13.jwelleryId = 13;
        j13.type = "Armlet";
        j13.material = "Gold";
        j13.brand = "Kalyan";
        j13.weightInGrams = 14.7;
        j13.isHandcrafted = true;
        System.out.println("Jwellery ID: " + j13.jwelleryId);
        System.out.println("Type: " + j13.type);
        System.out.println("Material: " + j13.material);
        System.out.println("Brand: " + j13.brand);
        System.out.println("Weight: " + j13.weightInGrams);
        System.out.println("Handcrafted: " + j13.isHandcrafted);

        Jwellery j14 = new Jwellery();
        j14.jwelleryId = 14;
        j14.type = "Brooch";
        j14.material = "Silver";
        j14.brand = "Malabar";
        j14.weightInGrams = 6.9;
        j14.isHandcrafted = false;
        System.out.println("Jwellery ID: " + j14.jwelleryId);
        System.out.println("Type: " + j14.type);
        System.out.println("Material: " + j14.material);
        System.out.println("Brand: " + j14.brand);
        System.out.println("Weight: " + j14.weightInGrams);
        System.out.println("Handcrafted: " + j14.isHandcrafted);

        Jwellery j15 = new Jwellery();
        j15.jwelleryId = 15;
        j15.type = "Waist Belt";
        j15.material = "Gold";
        j15.brand = "Tribes India";
        j15.weightInGrams = 25.0;
        j15.isHandcrafted = true;
        System.out.println("Jwellery ID: " + j15.jwelleryId);
        System.out.println("Type: " + j15.type);
        System.out.println("Material: " + j15.material);
        System.out.println("Brand: " + j15.brand);
        System.out.println("Weight: " + j15.weightInGrams);
        System.out.println("Handcrafted: " + j15.isHandcrafted);

        Jwellery j16 = new Jwellery();
        j16.jwelleryId = 16;
        j16.type = "Hair Pin";
        j16.material = "Silver";
        j16.brand = "PC Jeweller";
        j16.weightInGrams = 2.2;
        j16.isHandcrafted = false;
        System.out.println("Jwellery ID: " + j16.jwelleryId);
        System.out.println("Type: " + j16.type);
        System.out.println("Material: " + j16.material);
        System.out.println("Brand: " + j16.brand);
        System.out.println("Weight: " + j16.weightInGrams);
        System.out.println("Handcrafted: " + j16.isHandcrafted);

        Jwellery j17 = new Jwellery();
        j17.jwelleryId = 17;
        j17.type = "Hair Clip";
        j17.material = "Pearl";
        j17.brand = "Caratlane";
        j17.weightInGrams = 3.7;
        j17.isHandcrafted = true;
        System.out.println("Jwellery ID: " + j17.jwelleryId);
        System.out.println("Type: " + j17.type);
        System.out.println("Material: " + j17.material);
        System.out.println("Brand: " + j17.brand);
        System.out.println("Weight: " + j17.weightInGrams);
        System.out.println("Handcrafted: " + j17.isHandcrafted);

        Jwellery j18 = new Jwellery();
        j18.jwelleryId = 18;
        j18.type = "Shoulder Drape";
        j18.material = "Gold";
        j18.brand = "Reliance Jewels";
        j18.weightInGrams = 20.0;
        j18.isHandcrafted = true;
        System.out.println("Jwellery ID: " + j18.jwelleryId);
        System.out.println("Type: " + j18.type);
        System.out.println("Material: " + j18.material);
        System.out.println("Brand: " + j18.brand);
        System.out.println("Weight: " + j18.weightInGrams);
        System.out.println("Handcrafted: " + j18.isHandcrafted);

        Jwellery j19 = new Jwellery();
        j19.jwelleryId = 19;
        j19.type = "Hair Chain";
        j19.material = "Gold";
        j19.brand = "Amrapali";
        j19.weightInGrams = 7.3;
        j19.isHandcrafted = false;
        System.out.println("Jwellery ID: " + j19.jwelleryId);
        System.out.println("Type: " + j19.type);
        System.out.println("Material: " + j19.material);
        System.out.println("Brand: " + j19.brand);
        System.out.println("Weight: " + j19.weightInGrams);
        System.out.println("Handcrafted: " + j19.isHandcrafted);

        Jwellery j20 = new Jwellery();
        j20.jwelleryId = 20;
        j20.type = "Beaded Necklace";
        j20.material = "Beads";
        j20.brand = "Tribal Earth";
        j20.weightInGrams = 16.6;
        j20.isHandcrafted = true;
        System.out.println("Jwellery ID: " + j20.jwelleryId);
        System.out.println("Type: " + j20.type);
        System.out.println("Material: " + j20.material);
        System.out.println("Brand: " + j20.brand);
        System.out.println("Weight: " + j20.weightInGrams);
        System.out.println("Handcrafted: " + j20.isHandcrafted);

        System.out.println("main ended");
    }
}
