class PipeRunner {
    public static void main(String[] args) {
        System.out.println("main started");

        Pipe pipe1 = new Pipe();
        pipe1.pipeId = 1;
        pipe1.material = "PVC";
        pipe1.length = 6.0;
        pipe1.diameter = 1.5;
        pipe1.isFlexible = false;
        pipe1.usage = "Water supply";
        System.out.println("Pipe 1 ID: " + pipe1.pipeId);
        System.out.println("Material: " + pipe1.material);
        System.out.println("Length: " + pipe1.length);
        System.out.println("Diameter: " + pipe1.diameter);
        System.out.println("Is Flexible: " + pipe1.isFlexible);
        System.out.println("Usage: " + pipe1.usage);

        Pipe pipe2 = new Pipe();
        pipe2.pipeId = 2;
        pipe2.material = "Copper";
        pipe2.length = 4.5;
        pipe2.diameter = 1.0;
        pipe2.isFlexible = false;
        pipe2.usage = "Gas line";
        System.out.println("Pipe 2 ID: " + pipe2.pipeId);
        System.out.println("Material: " + pipe2.material);
        System.out.println("Length: " + pipe2.length);
        System.out.println("Diameter: " + pipe2.diameter);
        System.out.println("Is Flexible: " + pipe2.isFlexible);
        System.out.println("Usage: " + pipe2.usage);

        Pipe pipe3 = new Pipe();
        pipe3.pipeId = 3;
        pipe3.material = "Steel";
        pipe3.length = 5.5;
        pipe3.diameter = 2.0;
        pipe3.isFlexible = false;
        pipe3.usage = "Industrial piping";
        System.out.println("Pipe 3 ID: " + pipe3.pipeId);
        System.out.println("Material: " + pipe3.material);
        System.out.println("Length: " + pipe3.length);
        System.out.println("Diameter: " + pipe3.diameter);
        System.out.println("Is Flexible: " + pipe3.isFlexible);
        System.out.println("Usage: " + pipe3.usage);

        Pipe pipe4 = new Pipe();
        pipe4.pipeId = 4;
        pipe4.material = "CPVC";
        pipe4.length = 3.0;
        pipe4.diameter = 0.75;
        pipe4.isFlexible = false;
        pipe4.usage = "Hot water line";
        System.out.println("Pipe 4 ID: " + pipe4.pipeId);
        System.out.println("Material: " + pipe4.material);
        System.out.println("Length: " + pipe4.length);
        System.out.println("Diameter: " + pipe4.diameter);
        System.out.println("Is Flexible: " + pipe4.isFlexible);
        System.out.println("Usage: " + pipe4.usage);

        Pipe pipe5 = new Pipe();
        pipe5.pipeId = 5;
        pipe5.material = "HDPE";
        pipe5.length = 10.0;
        pipe5.diameter = 3.0;
        pipe5.isFlexible = true;
        pipe5.usage = "Irrigation";
        System.out.println("Pipe 5 ID: " + pipe5.pipeId);
        System.out.println("Material: " + pipe5.material);
        System.out.println("Length: " + pipe5.length);
        System.out.println("Diameter: " + pipe5.diameter);
        System.out.println("Is Flexible: " + pipe5.isFlexible);
        System.out.println("Usage: " + pipe5.usage);

        Pipe pipe6 = new Pipe();
        pipe6.pipeId = 6;
        pipe6.material = "PEX";
        pipe6.length = 6.5;
        pipe6.diameter = 1.25;
        pipe6.isFlexible = true;
        pipe6.usage = "Domestic plumbing";
        System.out.println("Pipe 6 ID: " + pipe6.pipeId);
        System.out.println("Material: " + pipe6.material);
        System.out.println("Length: " + pipe6.length);
        System.out.println("Diameter: " + pipe6.diameter);
        System.out.println("Is Flexible: " + pipe6.isFlexible);
        System.out.println("Usage: " + pipe6.usage);

        Pipe pipe7 = new Pipe();
        pipe7.pipeId = 7;
        pipe7.material = "Galvanized Iron";
        pipe7.length = 7.0;
        pipe7.diameter = 2.5;
        pipe7.isFlexible = false;
        pipe7.usage = "Sewage";
        System.out.println("Pipe 7 ID: " + pipe7.pipeId);
        System.out.println("Material: " + pipe7.material);
        System.out.println("Length: " + pipe7.length);
        System.out.println("Diameter: " + pipe7.diameter);
        System.out.println("Is Flexible: " + pipe7.isFlexible);
        System.out.println("Usage: " + pipe7.usage);

        Pipe pipe8 = new Pipe();
        pipe8.pipeId = 8;
        pipe8.material = "Concrete";
        pipe8.length = 12.0;
        pipe8.diameter = 4.0;
        pipe8.isFlexible = false;
        pipe8.usage = "Drainage";
        System.out.println("Pipe 8 ID: " + pipe8.pipeId);
        System.out.println("Material: " + pipe8.material);
        System.out.println("Length: " + pipe8.length);
        System.out.println("Diameter: " + pipe8.diameter);
        System.out.println("Is Flexible: " + pipe8.isFlexible);
        System.out.println("Usage: " + pipe8.usage);

        Pipe pipe9 = new Pipe();
        pipe9.pipeId = 9;
        pipe9.material = "Clay";
        pipe9.length = 4.0;
        pipe9.diameter = 2.0;
        pipe9.isFlexible = false;
        pipe9.usage = "Old sewer lines";
        System.out.println("Pipe 9 ID: " + pipe9.pipeId);
        System.out.println("Material: " + pipe9.material);
        System.out.println("Length: " + pipe9.length);
        System.out.println("Diameter: " + pipe9.diameter);
        System.out.println("Is Flexible: " + pipe9.isFlexible);
        System.out.println("Usage: " + pipe9.usage);

        Pipe pipe10 = new Pipe();
        pipe10.pipeId = 10;
        pipe10.material = "Brass";
        pipe10.length = 3.5;
        pipe10.diameter = 1.0;
        pipe10.isFlexible = false;
        pipe10.usage = "Residential plumbing";
        System.out.println("Pipe 10 ID: " + pipe10.pipeId);
        System.out.println("Material: " + pipe10.material);
        System.out.println("Length: " + pipe10.length);
        System.out.println("Diameter: " + pipe10.diameter);
        System.out.println("Is Flexible: " + pipe10.isFlexible);
        System.out.println("Usage: " + pipe10.usage);

                Pipe pipe11 = new Pipe();
        pipe11.pipeId = 11;
        pipe11.material = "Aluminum";
        pipe11.length = 8.0;
        pipe11.diameter = 2.25;
        pipe11.isFlexible = true;
        pipe11.usage = "HVAC ducting";
        System.out.println("Pipe 11 ID: " + pipe11.pipeId);
        System.out.println("Material: " + pipe11.material);
        System.out.println("Length: " + pipe11.length);
        System.out.println("Diameter: " + pipe11.diameter);
        System.out.println("Is Flexible: " + pipe11.isFlexible);
        System.out.println("Usage: " + pipe11.usage);

        Pipe pipe12 = new Pipe();
        pipe12.pipeId = 12;
        pipe12.material = "Lead";
        pipe12.length = 3.0;
        pipe12.diameter = 0.5;
        pipe12.isFlexible = false;
        pipe12.usage = "Old plumbing";
        System.out.println("Pipe 12 ID: " + pipe12.pipeId);
        System.out.println("Material: " + pipe12.material);
        System.out.println("Length: " + pipe12.length);
        System.out.println("Diameter: " + pipe12.diameter);
        System.out.println("Is Flexible: " + pipe12.isFlexible);
        System.out.println("Usage: " + pipe12.usage);

        Pipe pipe13 = new Pipe();
        pipe13.pipeId = 13;
        pipe13.material = "Fiber Glass";
        pipe13.length = 9.0;
        pipe13.diameter = 3.5;
        pipe13.isFlexible = false;
        pipe13.usage = "Chemical transport";
        System.out.println("Pipe 13 ID: " + pipe13.pipeId);
        System.out.println("Material: " + pipe13.material);
        System.out.println("Length: " + pipe13.length);
        System.out.println("Diameter: " + pipe13.diameter);
        System.out.println("Is Flexible: " + pipe13.isFlexible);
        System.out.println("Usage: " + pipe13.usage);

        Pipe pipe14 = new Pipe();
        pipe14.pipeId = 14;
        pipe14.material = "Cast Iron";
        pipe14.length = 6.0;
        pipe14.diameter = 2.5;
        pipe14.isFlexible = false;
        pipe14.usage = "Drainage";
        System.out.println("Pipe 14 ID: " + pipe14.pipeId);
        System.out.println("Material: " + pipe14.material);
        System.out.println("Length: " + pipe14.length);
        System.out.println("Diameter: " + pipe14.diameter);
        System.out.println("Is Flexible: " + pipe14.isFlexible);
        System.out.println("Usage: " + pipe14.usage);

        Pipe pipe15 = new Pipe();
        pipe15.pipeId = 15;
        pipe15.material = "Rubber";
        pipe15.length = 5.0;
        pipe15.diameter = 1.75;
        pipe15.isFlexible = true;
        pipe15.usage = "Temporary connections";
        System.out.println("Pipe 15 ID: " + pipe15.pipeId);
        System.out.println("Material: " + pipe15.material);
        System.out.println("Length: " + pipe15.length);
        System.out.println("Diameter: " + pipe15.diameter);
        System.out.println("Is Flexible: " + pipe15.isFlexible);
        System.out.println("Usage: " + pipe15.usage);

        Pipe pipe16 = new Pipe();
        pipe16.pipeId = 16;
        pipe16.material = "Plastic";
        pipe16.length = 7.0;
        pipe16.diameter = 1.5;
        pipe16.isFlexible = true;
        pipe16.usage = "Aquarium piping";
        System.out.println("Pipe 16 ID: " + pipe16.pipeId);
        System.out.println("Material: " + pipe16.material);
        System.out.println("Length: " + pipe16.length);
        System.out.println("Diameter: " + pipe16.diameter);
        System.out.println("Is Flexible: " + pipe16.isFlexible);
        System.out.println("Usage: " + pipe16.usage);

        Pipe pipe17 = new Pipe();
        pipe17.pipeId = 17;
        pipe17.material = "Silicone";
        pipe17.length = 2.0;
        pipe17.diameter = 0.75;
        pipe17.isFlexible = true;
        pipe17.usage = "Lab setups";
        System.out.println("Pipe 17 ID: " + pipe17.pipeId);
        System.out.println("Material: " + pipe17.material);
        System.out.println("Length: " + pipe17.length);
        System.out.println("Diameter: " + pipe17.diameter);
        System.out.println("Is Flexible: " + pipe17.isFlexible);
        System.out.println("Usage: " + pipe17.usage);

        Pipe pipe18 = new Pipe();
        pipe18.pipeId = 18;
        pipe18.material = "Carbon Steel";
        pipe18.length = 8.5;
        pipe18.diameter = 3.0;
        pipe18.isFlexible = false;
        pipe18.usage = "Heavy industries";
        System.out.println("Pipe 18 ID: " + pipe18.pipeId);
        System.out.println("Material: " + pipe18.material);
        System.out.println("Length: " + pipe18.length);
        System.out.println("Diameter: " + pipe18.diameter);
        System.out.println("Is Flexible: " + pipe18.isFlexible);
        System.out.println("Usage: " + pipe18.usage);

        Pipe pipe19 = new Pipe();
        pipe19.pipeId = 19;
        pipe19.material = "Vinyl";
        pipe19.length = 4.0;
        pipe19.diameter = 1.0;
        pipe19.isFlexible = true;
        pipe19.usage = "Garden hoses";
        System.out.println("Pipe 19 ID: " + pipe19.pipeId);
        System.out.println("Material: " + pipe19.material);
        System.out.println("Length: " + pipe19.length);
        System.out.println("Diameter: " + pipe19.diameter);
        System.out.println("Is Flexible: " + pipe19.isFlexible);
        System.out.println("Usage: " + pipe19.usage);

        Pipe pipe20 = new Pipe();
        pipe20.pipeId = 20;
        pipe20.material = "Stainless Steel";
        pipe20.length = 9.0;
        pipe20.diameter = 2.0;
        pipe20.isFlexible = false;
        pipe20.usage = "Food processing";
        System.out.println("Pipe 20 ID: " + pipe20.pipeId);
        System.out.println("Material: " + pipe20.material);
        System.out.println("Length: " + pipe20.length);
        System.out.println("Diameter: " + pipe20.diameter);
        System.out.println("Is Flexible: " + pipe20.isFlexible);
        System.out.println("Usage: " + pipe20.usage);

        System.out.println("main ended");
    }
}

